alphatrion_mobilenet_v2_fp32: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.20, '>', '5%']
  __benchmark_mem_alloc(mb): [2800, '>', '5%']
  __benchmark_mem_cached(mb): [3300, '>', '5%']
  __benchmark_pure_training_time(h): [0.31, '>', '5%']
  __benchmark_total_time(h): [0.33, '>', '5%']
  valid-metric-sub-epoch-best/top1: [10000, '<', '5%']
alphatrion_mobilenet_v2_fp16:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.20, '>', '5%']
  __benchmark_mem_alloc(mb): [2800, '>', '5%']
  __benchmark_mem_cached(mb): [3300, '>', '5%']
  __benchmark_pure_training_time(h): [0.30, '>', '5%']
  __benchmark_total_time(h): [0.30, '>', '5%']
  valid-metric-sub-epoch-best/top1: [10000, '<', '5%']
alphatrion_se_resnet50_fp32:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.43, '>', '5%']
  __benchmark_mem_alloc(mb): [5500, '>', '5%']
  __benchmark_mem_cached(mb): [6800, '>', '5%']
  __benchmark_pure_training_time(h): [0.65, '>', '5%']
  __benchmark_total_time(h): [0.65, '>', '5%']
  valid-metric-sub-epoch-best/top1: [10000, '<', '5%']
alphatrion_se_resnet50_fp16:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.30, '>', '5%']
  __benchmark_mem_alloc(mb): [3500, '>', '5%']
  __benchmark_mem_cached(mb): [4600, '>', '5%']
  __benchmark_pure_training_time(h): [0.45, '>', '5%']
  __benchmark_total_time(h): [0.45, '>', '5%']
  valid-metric-sub-epoch-best/top1: [10000, '<', '5%']
alphatrion_resnet50_fp32:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.30, '>', '5%']
  __benchmark_mem_alloc(mb): [5400, '>', '5%']
  __benchmark_mem_cached(mb): [5800, '>', '5%']
  __benchmark_pure_training_time(h): [0.44, '>', '5%']
  __benchmark_total_time(h): [0.45, '>', '5%']
  valid-metric-sub-epoch-best/top1: [10000, '<', '5%']
alphatrion_resnet50_fp16:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.40, '>', '5%']
  __benchmark_mem_alloc(mb): [4400, '>', '5%']
  __benchmark_mem_cached(mb): [5500, '>', '5%']
  __benchmark_pure_training_time(h): [0.57, '>', '5%']
  __benchmark_total_time(h): [0.57, '>', '5%']
  valid-metric-sub-epoch-best/top1: [10000, '<', '5%']
alphatrion_resnet101_fp32:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.45, '>', '5%']
  __benchmark_mem_alloc(mb): [7300, '>', '5%']
  __benchmark_mem_cached(mb): [7900, '>', '5%']
  __benchmark_pure_training_time(h): [0.66, '>', '5%']
  __benchmark_total_time(h): [0.67, '>', '5%']
  valid-metric-sub-epoch-best/top1: [10000, '<', '5%']
alphatrion_resnet101_fp16:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.39, '>', '5%']
  __benchmark_mem_alloc(mb): [4400, '>', '5%']
  __benchmark_mem_cached(mb): [5500, '>', '5%']
  __benchmark_pure_training_time(h): [0.57, '>', '5%']
  __benchmark_total_time(h): [0.58, '>', '5%']
  valid-metric-sub-epoch-best/top1: [10000, '<', '5%']
alphatrion_mobilenet_v2_fp32_benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.20, '>', '5%']
  __benchmark_mem_alloc(mb): [2800, '>', '5%']
  __benchmark_mem_cached(mb): [3300, '>', '5%']
  __benchmark_pure_training_time(h): [0.31, '>', '5%']
  __benchmark_total_time(h): [0.33, '>', '5%']
alphatrion_mobilenet_v2_fp16_benchmark:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.20, '>', '5%']
  __benchmark_mem_alloc(mb): [2800, '>', '5%']
  __benchmark_mem_cached(mb): [3300, '>', '5%']
  __benchmark_pure_training_time(h): [0.30, '>', '5%']
  __benchmark_total_time(h): [0.30, '>', '5%']
alphatrion_se_resnet50_fp32_benchmark:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.43, '>', '5%']
  __benchmark_mem_alloc(mb): [5500, '>', '5%']
  __benchmark_mem_cached(mb): [6800, '>', '5%']
  __benchmark_pure_training_time(h): [0.65, '>', '5%']
  __benchmark_total_time(h): [0.65, '>', '5%']
alphatrion_se_resnet50_fp16_benchmark:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.30, '>', '5%']
  __benchmark_mem_alloc(mb): [3500, '>', '5%']
  __benchmark_mem_cached(mb): [4600, '>', '5%']
  __benchmark_pure_training_time(h): [0.45, '>', '5%']
  __benchmark_total_time(h): [0.45, '>', '5%']
alphatrion_resnet50_fp32_benchmark:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.30, '>', '5%']
  __benchmark_mem_alloc(mb): [5400, '>', '5%']
  __benchmark_mem_cached(mb): [5800, '>', '5%']
  __benchmark_pure_training_time(h): [0.44, '>', '5%']
  __benchmark_total_time(h): [0.45, '>', '5%']
alphatrion_resnet50_fp16_benchmark:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.40, '>', '5%']
  __benchmark_mem_alloc(mb): [4400, '>', '5%']
  __benchmark_mem_cached(mb): [5500, '>', '5%']
  __benchmark_pure_training_time(h): [0.57, '>', '5%']
  __benchmark_total_time(h): [0.57, '>', '5%']
alphatrion_resnet101_fp32_benchmark:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.45, '>', '5%']
  __benchmark_mem_alloc(mb): [7300, '>', '5%']
  __benchmark_mem_cached(mb): [7900, '>', '5%']
  __benchmark_pure_training_time(h): [0.66, '>', '5%']
  __benchmark_total_time(h): [0.67, '>', '5%']
alphatrion_resnet101_fp16_benchmark:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.39, '>', '5%']
  __benchmark_mem_alloc(mb): [4400, '>', '5%']
  __benchmark_mem_cached(mb): [5500, '>', '5%']
  __benchmark_pure_training_time(h): [0.57, '>', '5%']
  __benchmark_total_time(h): [0.58, '>', '5%']
