alphatrion_mobilenet_v2_fp32: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  valid-metric-sub-epoch-best/top1: [10000, '>', '20%']

alphatrion_mobilenet_v2_fp16:
  # attr: [thresh, has_to_higher/has_to_lower]
  valid-metric-sub-epoch-best/top1: [10000, '>', '20%']

alphatrion_se_resnet50_fp32:
  # attr: [thresh, has_to_higher/has_to_lower]
  valid-metric-sub-epoch-best/top1: [10000, '>', '20%']

alphatrion_se_resnet50_fp16:
  # attr: [thresh, has_to_higher/has_to_lower]
  valid-metric-sub-epoch-best/top1: [10000, '>', '20%']

alphatrion_resnet50_fp32:
  # attr: [thresh, has_to_higher/has_to_lower]
  valid-metric-sub-epoch-best/top1: [10000, '>', '20%']

alphatrion_resnet50_fp16:
  # attr: [thresh, has_to_higher/has_to_lower]
  valid-metric-sub-epoch-best/top1: [10000, '>', '20%']

alphatrion_resnet101_fp32:
  # attr: [thresh, has_to_higher/has_to_lower]
  valid-metric-sub-epoch-best/top1: [10000, '>', '20%']

alphatrion_resnet101_fp16:
  # attr: [thresh, has_to_higher/has_to_lower]
  valid-metric-sub-epoch-best/top1: [10000, '>', '20%']

alphatrion_mobilenet_v2_fp32_benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

alphatrion_mobilenet_v2_fp16_benchmark:
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

alphatrion_se_resnet50_fp32_benchmark:
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

alphatrion_se_resnet50_fp16_benchmark:
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

alphatrion_resnet50_fp32_benchmark:
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

alphatrion_resnet50_fp16_benchmark:
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

alphatrion_resnet101_fp32_benchmark:
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

alphatrion_resnet101_fp16_benchmark:
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'
