alphatrion_nas_super_resnet_range1: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  max_origin_valid-metric-sub-epoch-best/top1: [10000, '>', '20%']

alphatrion_nas_super_resnet_range1_fp16: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  max_origin_valid-metric-sub-epoch-best/top1: [10000, '>', '20%']

alphatrion_nas_super_resnet_range1_benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

alphatrion_nas_super_resnet_range1_fp16_benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'
