example_resnet50: # Required.
  Accuracy_Test_top1: [0, '>', '20%']

example_resnet50.short: # Required.
  Accuracy_Test_top1: [0, '>', '20%']

example_resnet50.short.dummy_data: # Required.
  placeholder: 'none'

example_resnet50.benchmark: # Required.
  placeholder: 'none'

example_resnet50_sync.short: # Required.
  Accuracy_Test_top1: [0, '>', '20%']

example_resnet50_sync.short.dummy_data: # Required.
  placeholder: 'none'

example_resnet50_sync.benchmark: # Required.
  placeholder: 'none'

example_resnet50_mix: # Required.
  Accuracy_Test_top1: [0, '>', '20%'] # 15.790 - 1

example_resnet50_mix.benchmark: # Required.
  placeholder: 'none'

example_se_resnet50: # Required.
  Accuracy_Test_top1: [0, '>', '20%'] # 18.200 - 1

example_se_resnet50.short: # Required.
  Accuracy_Test_top1: [0, '>', '20%'] # 18.200 - 1

example_se_resnet50.benchmark: # Required.
  placeholder: 'none'

example_se_resnet50_mix: # Required.
  Accuracy_Test_top1: [0, '>', '20%'] # 16.436 - 1

example_se_resnet50_mix.benchmark: # Required.
  placeholder: 'none'

example_inception_v4: # Required.
  Accuracy_Test_top1: [0, '>', '20%'] # 15.690 - 1

example_inception_v4.benchmark: # Required.
  placeholder: 'none'

example_inception_v4_mix: # Required.
  Accuracy_Test_top1: [0, '>', '20%'] # 17.874 - 1

example_inception_v4_mix.benchmark: # Required.
  placeholder: 'none'

example_shuffle_v2: # Required.
  Accuracy_Test_top1: [0, '>', '20%'] # 14.796 - 1

example_shuffle_v2.benchmark: # Required.
  placeholder: 'none'

example_shuffle_v2_mix: # Required.
  Accuracy_Test_top1: [0, '>', '20%'] # 15.000 - 1

example_shuffle_v2_mix.benchmark: # Required.
  placeholder: 'none'

example_mobile_v2: # Required.
  Accuracy_Test_top1: [0, '>', '20%'] # 19.342 - 1

example_mobile_v2.benchmark: # Required.
  placeholder: 'none'

example_mobile_v2_mix: # Required.
  Accuracy_Test_top1: [0, '>', '20%'] # 19.872 - 1

example_mobile_v2_mix.benchmark: # Required.
  placeholder: 'none'

example_resnet18: # Required.
  Accuracy_Test_top1: [0, '>', '20%'] # 21.484 - 1

example_resnet18.benchmark: # Required.
  placeholder: 'none'

example_resnet18_mix: # Required.
  Accuracy_Test_top1: [0, '>', '20%'] # 20.586 - 1

example_resnet18_mix.short: # Required.
  Accuracy_Test_top1: [0, '>', '20%'] # 20.586 - 1

example_resnet18_mix.benchmark: # Required.
  placeholder: 'none'

example_resnet101: # Required.
  Accuracy_Test_top1: [0, '>', '20%'] # 20.586 - 1

example_resnet101.benchmark: # Required.
  placeholder: 'none'

example_resnet101_mix: # Required.
  Accuracy_Test_top1: [0, '>', '20%'] # 10.250 - 1

example_resnet101_mix.benchmark: # Required.
  placeholder: 'none'

example_resnet152: # Required.
  Accuracy_Test_top1: [0, '>', '20%'] # 11.976 - 1

example_resnet152.benchmark: # Required.
  placeholder: 'none'

example_resnet152_mix: # Required.
  Accuracy_Test_top1: [0, '>', '20%'] # 12.198 - 1

example_resnet152_mix.benchmark: # Required.
  placeholder: 'none'

example_inception_v2: # Required.
  Accuracy_Test_top1: [0, '>', '20%']

example_inception_v2.benchmark: # Required.
  placeholder: 'none'

example_inception_v2_mix: # Required.
  Accuracy_Test_top1: [0, '>', '20%']

example_inception_v2_mix.benchmark: # Required.
  placeholder: 'none'

example_inception_v3: # Required.
  Accuracy_Test_top1: [11.198, '>', '20%'] # 12.198 - 1

example_inception_v3.short: # Required.
  Accuracy_Test_top1: [0, '>', '20%']

example_inception_v3.benchmark: # Required.
  placeholder: 'none'

example_inception_v3_mix: # Required.
  Accuracy_Test_top1: [0, '>', '20%']

example_inception_v3_mix.benchmark: # Required.
  placeholder: 'none'

example_dpn92: # Required.
  Accuracy_Test_top1: [0, '>', '20%']

example_dpn92.benchmark: # Required.
  placeholder: 'none'

example_dpn92_mix: # Required.
  Accuracy_Test_top1: [0, '>', '20%']

example_dpn92_mix.benchmark: # Required.
  placeholder: 'none'

example_inception_resnet: # Required.
  Accuracy_Test_top1: [0, '>', '20%']

example_inception_resnet.benchmark: # Required.
  placeholder: 'none'

example_inception_resnet_mix: # Required.
  Accuracy_Test_top1: [0, '>', '20%']

example_inception_resnet_mix.benchmark: # Required.
  placeholder: 'none'

example_inceptionv3_daily: # Required.
  Accuracy_Test_top1: [0, '>', '20%']

example_mobile_v1_daily: # Required.
  Accuracy_Test_top1: [0, '>', '20%']

example_resnet50_daily: # Required.
  Accuracy_Test_top1: [0, '>', '20%']

example_resnet50_weekly: # Required.
  Accuracy_Test_top1: [0, '>', '20%']

example_resnet50_mix_weekly: # Required.
  Accuracy_Test_top1: [0, '>', '20%']

example_se_resnet50_mix_weekly: # Required
  Accuracy_Test_top1: [0, '>', '20%']

example_inception_v4_weekly: # Required.
  Accuracy_Test_top1: [0, '>', '20%']

example_shuffle_v2_weekly: # Required.
  Accuracy_Test_top1: [0, '>', '20%']

example_mobile_v2_weekly: # Required.
  Accuracy_Test_top1: [0, '>', '20%']

example_mobile_v1.short: # Required.
  Accuracy_Test_top1: [0, '>', '20%']

example_mobile_v1.short.dummy_data: # Required.
  placeholder: 'none'

example_mobile_v1.benchmark: # Required.
  placeholder: 'none'

example_inceptionv3.short: # Required.  __benchmark_avg_iter_time(s): [100000, '<', '50%']
  Accuracy_Test_top1: [0, '>', '20%']

example_inceptionv3.short.dummy_data: # Required.  __benchmark_avg_iter_time(s): [100000, '<', '50%']
  placeholder: 'none'

example_vgg16.benchmark: # Required.
  placeholder: 'none'

example_shuffle_v1.benchmark: # Required.
  placeholder: 'none'

example_resnet18_mix.short.dummy_data:
  placeholder: 'none'
