example_dpn92:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_dpn92.benchmark:
  placeholder: none
example_dpn92_mix:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_dpn92_mix.benchmark:
  placeholder: none
example_inception_resnet:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_inception_resnet.benchmark:
  placeholder: none
example_inception_resnet_mix:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_inception_resnet_mix.benchmark:
  placeholder: none
example_inception_v2:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_inception_v2.benchmark:
  placeholder: none
example_inception_v2_mix:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_inception_v2_mix.benchmark:
  placeholder: none
example_inception_v3:
  Accuracy_Test_top1:
  - 11.198
  - '>'
  - 20%
example_inception_v3.benchmark:
  placeholder: none
example_inception_v3.short:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_inception_v3_mix:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_inception_v3_mix.benchmark:
  placeholder: none
example_inception_v4:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
  weeklytest:
    __benchmark_avg_iter_time(s):
    - 0.31359564195765127
    - <
    - 50%
    - 0.20906376130510085
    __benchmark_mem_alloc(mb):
    - 11823.0
    - <
    - 50%
    - 7882
    __benchmark_mem_cached(mb):
    - 12120.0
    - <
    - 50%
    - 8080
    __benchmark_pavi_task_id:
    - 6038f047-eaf6-431c-8f35-3e188fd24150
    __benchmark_pure_training_time(h):
    - 0.49209322849909465
    - <
    - 50%
    - 0.3280621523327298
    __benchmark_total_time(h):
    - 71
    - <
    - 50%
    - 69
example_inception_v4.benchmark:
  placeholder: none
example_inception_v4_mix:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_inception_v4_mix.benchmark:
  placeholder: none
example_inception_v4_weekly:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_inceptionv3.short:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
  dailytest:
    __benchmark_avg_iter_time(s):
    - 0.31359564195765127
    - <
    - 50%
    - 0.20906376130510085
    __benchmark_mem_alloc(mb):
    - 11823.0
    - <
    - 50%
    - 7882
    __benchmark_mem_cached(mb):
    - 12120.0
    - <
    - 50%
    - 8080
    __benchmark_pavi_task_id:
    - 6038f047-eaf6-431c-8f35-3e188fd24150
    __benchmark_pure_training_time(h):
    - 0.49209322849909465
    - <
    - 50%
    - 0.3280621523327298
    __benchmark_total_time(h):
    - 1.64
    - <
    - 50%
    - 1.14
example_inceptionv3.short.dummy_data:
  placeholder: none
example_inceptionv3_daily:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_mobile_v1.benchmark:
  placeholder: none
example_mobile_v1.short:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
  dailytest:
    __benchmark_avg_iter_time(s):
    - 0.31359564195765127
    - <
    - 50%
    - 0.20906376130510085
    __benchmark_mem_alloc(mb):
    - 11823.0
    - <
    - 50%
    - 7882
    __benchmark_mem_cached(mb):
    - 12120.0
    - <
    - 50%
    - 8080
    __benchmark_pavi_task_id:
    - 6038f047-eaf6-431c-8f35-3e188fd24150
    __benchmark_pure_training_time(h):
    - 0.49209322849909465
    - <
    - 50%
    - 0.3280621523327298
    __benchmark_total_time(h):
    - 1.5
    - <
    - 50%
    - 1.0
example_mobile_v1.short.dummy_data:
  placeholder: none
example_mobile_v1_daily:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_mobile_v2:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
  weeklytest:
    __benchmark_avg_iter_time(s):
    - 0.31359564195765127
    - <
    - 50%
    - 0.20906376130510085
    __benchmark_mem_alloc(mb):
    - 11823.0
    - <
    - 50%
    - 7882
    __benchmark_mem_cached(mb):
    - 12120.0
    - <
    - 50%
    - 8080
    __benchmark_pavi_task_id:
    - 6038f047-eaf6-431c-8f35-3e188fd24150
    __benchmark_pure_training_time(h):
    - 0.49209322849909465
    - <
    - 50%
    - 0.3280621523327298
    __benchmark_total_time(h):
    - 67
    - <
    - 50%
    - 65
example_mobile_v2.benchmark:
  placeholder: none
example_mobile_v2_mix:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
  weeklytest:
    Accuracy_Test_top1:
    - 55.3024
    - '>'
    - 20%
    - 69.128
    __benchmark_avg_iter_time(s):
    - 0.18052866583439842
    - <
    - 5%
    - 0.17193206269942707
    __benchmark_mem_alloc(mb):
    - 2358.3
    - <
    - 5%
    - 2246
    __benchmark_mem_cached(mb):
    - 3418.8
    - <
    - 5%
    - 3256
    __benchmark_pavi_task_id:
    - ac089d0b-255d-4bf2-97d7-6564f7ceafe4
    __benchmark_pure_training_time(h):
    - 60.51732146195571
    - <
    - 5%
    - 57.635544249481626
    __benchmark_total_time(h):
    - 60.51859066643317
    - <
    - 5%
    - 57.63675301565064
    test_life: 1
example_mobile_v2_mix.benchmark:
  placeholder: none
example_mobile_v2_weekly:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_resnet101:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_resnet101.benchmark:
  placeholder: none
example_resnet101_mix:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_resnet101_mix.benchmark:
  placeholder: none
example_resnet152:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_resnet152.benchmark:
  placeholder: none
example_resnet152_mix:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_resnet152_mix.benchmark:
  placeholder: none
example_resnet18:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_resnet18.benchmark:
  placeholder: none
example_resnet18.short:
  placeholder: none
example_resnet18_mix:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_resnet18_mix.benchmark:
  placeholder: none
example_resnet18_mix.short:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
  dailytest:
    __benchmark_avg_iter_time(s):
    - 0.31359564195765127
    - <
    - 50%
    - 0.20906376130510085
    __benchmark_mem_alloc(mb):
    - 11823.0
    - <
    - 50%
    - 7882
    __benchmark_mem_cached(mb):
    - 12120.0
    - <
    - 50%
    - 8080
    __benchmark_pavi_task_id:
    - 6038f047-eaf6-431c-8f35-3e188fd24150
    __benchmark_pure_training_time(h):
    - 0.49209322849909465
    - <
    - 50%
    - 0.3280621523327298
    __benchmark_total_time(h):
    - 1.01
    - <
    - 50%
    - 0.31
example_resnet18_mix.short.dummy_data:
  placeholder: none
example_resnet50:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
  weeklytest:
    __benchmark_avg_iter_time(s):
    - 0.31359564195765127
    - <
    - 50%
    - 0.20906376130510085
    __benchmark_mem_alloc(mb):
    - 11823.0
    - <
    - 50%
    - 7882
    __benchmark_mem_cached(mb):
    - 12120.0
    - <
    - 50%
    - 8080
    __benchmark_pavi_task_id:
    - 6038f047-eaf6-431c-8f35-3e188fd24150
    __benchmark_pure_training_time(h):
    - 0.49209322849909465
    - <
    - 50%
    - 0.3280621523327298
    __benchmark_total_time(h):
    - 32.5
    - <
    - 50%
    - 30.5
example_resnet50.benchmark:
  placeholder: none
example_resnet50.short:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
  dailytest:
    __benchmark_avg_iter_time(s):
    - 0.31359564195765127
    - <
    - 50%
    - 0.20906376130510085
    __benchmark_mem_alloc(mb):
    - 11823.0
    - <
    - 50%
    - 7882
    __benchmark_mem_cached(mb):
    - 12120.0
    - <
    - 50%
    - 8080
    __benchmark_pavi_task_id:
    - 6038f047-eaf6-431c-8f35-3e188fd24150
    __benchmark_pure_training_time(h):
    - 0.49209322849909465
    - <
    - 50%
    - 0.3280621523327298
    __benchmark_total_time(h):
    - 1.52
    - <
    - 50%
    - 1.02
example_resnet50.short.dummy_data:
  placeholder: none
example_resnet50_daily:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_resnet50_mix:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
  weeklytest:
    __benchmark_avg_iter_time(s):
    - 0.31359564195765127
    - <
    - 50%
    - 0.20906376130510085
    __benchmark_mem_alloc(mb):
    - 11823.0
    - <
    - 50%
    - 7882
    __benchmark_mem_cached(mb):
    - 12120.0
    - <
    - 50%
    - 8080
    __benchmark_pavi_task_id:
    - 6038f047-eaf6-431c-8f35-3e188fd24150
    __benchmark_pure_training_time(h):
    - 0.49209322849909465
    - <
    - 50%
    - 0.3280621523327298
    __benchmark_total_time(h):
    - 32.25
    - <
    - 50%
    - 30.25
example_resnet50_mix.benchmark:
  placeholder: none
example_resnet50_mix_weekly:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_resnet50_sync.benchmark:
  placeholder: none
example_resnet50_sync.short:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
  dailytest:
    __benchmark_avg_iter_time(s):
    - 0.31359564195765127
    - <
    - 50%
    - 0.20906376130510085
    __benchmark_mem_alloc(mb):
    - 11823.0
    - <
    - 50%
    - 7882
    __benchmark_mem_cached(mb):
    - 12120.0
    - <
    - 50%
    - 8080
    __benchmark_pavi_task_id:
    - 6038f047-eaf6-431c-8f35-3e188fd24150
    __benchmark_pure_training_time(h):
    - 0.49209322849909465
    - <
    - 50%
    - 0.3280621523327298
    __benchmark_total_time(h):
    - 1.53
    - <
    - 50%
    - 1.03
example_resnet50_sync.short.dummy_data:
  placeholder: none
example_resnet50_weekly:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_se_resnet50:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_se_resnet50.benchmark:
  placeholder: none
example_se_resnet50.short:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_se_resnet50_mix:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
  weeklytest:
    __benchmark_avg_iter_time(s):
    - 0.31359564195765127
    - <
    - 50%
    - 0.20906376130510085
    __benchmark_mem_alloc(mb):
    - 11823.0
    - <
    - 50%
    - 7882
    __benchmark_mem_cached(mb):
    - 12120.0
    - <
    - 50%
    - 8080
    __benchmark_pavi_task_id:
    - 6038f047-eaf6-431c-8f35-3e188fd24150
    __benchmark_pure_training_time(h):
    - 0.49209322849909465
    - <
    - 50%
    - 0.3280621523327298
    __benchmark_total_time(h):
    - 32
    - <
    - 50%
    - 30
example_se_resnet50_mix.benchmark:
  placeholder: none
example_se_resnet50_mix_weekly:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_shuffle_v1.benchmark:
  placeholder: none
example_shuffle_v2:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
  weeklytest:
    __benchmark_avg_iter_time(s):
    - 0.31359564195765127
    - <
    - 50%
    - 0.20906376130510085
    __benchmark_mem_alloc(mb):
    - 11823.0
    - <
    - 50%
    - 7882
    __benchmark_mem_cached(mb):
    - 12120.0
    - <
    - 50%
    - 8080
    __benchmark_pavi_task_id:
    - 6038f047-eaf6-431c-8f35-3e188fd24150
    __benchmark_pure_training_time(h):
    - 0.49209322849909465
    - <
    - 50%
    - 0.3280621523327298
    __benchmark_total_time(h):
    - 61.33
    - <
    - 50%
    - 59.33
example_shuffle_v2.benchmark:
  placeholder: none
example_shuffle_v2_mix:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
  weeklytest:
    Accuracy_Test_top1:
    - 52.00320000000001
    - '>'
    - 20%
    - 65.004
    __benchmark_avg_iter_time(s):
    - 0.18010737308815344
    - <
    - 5%
    - 0.1715308315125271
    __benchmark_mem_alloc(mb):
    - 1425.9
    - <
    - 5%
    - 1358
    __benchmark_mem_cached(mb):
    - 2284.8
    - <
    - 5%
    - 2176
    __benchmark_pavi_task_id:
    - 1bb0b2b8-aa9f-4adc-8370-a7b14798b9ac
    __benchmark_pure_training_time(h):
    - 60.73502469066779
    - <
    - 5%
    - 57.84288065777885
    __benchmark_total_time(h):
    - 60.736160667936005
    - <
    - 5%
    - 57.84396254089143
    test_life: 1
example_shuffle_v2_mix.benchmark:
  placeholder: none
example_shuffle_v2_weekly:
  Accuracy_Test_top1:
  - 0
  - '>'
  - 20%
example_vgg16.benchmark:
  placeholder: none
