mild_base_mbv2: # Required
  func: mild_func
  args:
    done_flag: "Pipeline is Done"
  thresh: # Required
    total_time: 35.0
    iter_speed: 0.31
    cls_loss: 20
    mimic_loss: 0.7
mild_base_r100: # Required
  func: mild_func
  args:
    done_flag: "Pipeline is Done"
  thresh: # Required
    total_time: 35.0
    iter_speed: 0.31
    cls_loss: 20
    mimic_loss: 0.7
mild_base_xmeta: # Required
  func: mild_func
  args:
    done_flag: "Pipeline is Done"
  thresh: # Required
    total_time: 35.0
    iter_speed: 0.31
    cls_loss: 20
    mimic_loss: 0.7
