# all epoch
mmaction_i3d_r50_video_32x2x1_100e_kinetics400_rgb:
  func: mmaction_func
  args:
    done_flag: "Pipeline is Done"
  thresh:
    iter_speed: None
    top1_acc: None
    total_time(h): None

mmaction_tsn_r50_video_1x1x8_100e_kinetics400_rgb:
  func: mmaction_func
  args:
    done_flag: "Pipeline is Done"
  thresh:
    iter_speed: None
    top1_acc: 69.22
    total_time(h): None

mmaction_tsn_r50_video_dense_1x1x8_100e_kinetics400_rgb:
  func: mmaction_func
  args:
    done_flag: "Pipeline is Done"
  thresh:
    iter_speed: None
    top1_acc: 70.21
    total_time(h): None

# benchmark 1 epoch
mmaction_i3d_r50_video_32x2x1_100e_kinetics400_rgb.benchmark:
  func: mmaction_func
  args:
    done_flag: "Pipeline is Done"
  thresh:
    iter_speed: 0.5796
    top1_acc: 0.0137
    total_time(h): 0.7

mmaction_tsn_r50_video_1x1x8_100e_kinetics400_rgb.benchmark:
  func: mmaction_func
  args:
    done_flag: "Pipeline is Done"
  thresh:
    iter_speed: 2.0375
    top1_acc: 0.1722
    total_time(h): 0.6

mmaction_tsn_r50_video_dense_1x1x8_100e_kinetics400_rgb.benchmark:
  func: mmaction_func
  args:
    done_flag: "Pipeline is Done"
  thresh:
    iter_speed: 1.4417
    top1_acc: 0.1581
    total_time(h): 0.5