mmaction_i3d_r50_video_32x2x1_100e_kinetics400_rgb:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '>', '5%']
  __benchmark_mem_alloc(mb): [10000, '>', '5%']
  __benchmark_mem_cached(mb): [10000, '>', '5%']
  __benchmark_pure_training_time(h): [10000, '>', '5%']
  __benchmark_total_time(h): [10000, '>', '5%']
  train.top1_acc: [10000, '<', '5%']

mmaction_r2plus1d_r34_video_8x8x1_180e_kinetics400_rgb:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '>', '5%']
  __benchmark_mem_alloc(mb): [10000, '>', '5%']
  __benchmark_mem_cached(mb): [10000, '>', '5%']
  __benchmark_pure_training_time(h): [10000, '>', '5%']
  __benchmark_total_time(h): [10000, '>', '5%']
  train.top1_acc: [10000, '<', '5%']

mmaction_slowfast_r50_video_4x16x1_256e_kinetics400_rgb:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '>', '5%']
  __benchmark_mem_alloc(mb): [10000, '>', '5%']
  __benchmark_mem_cached(mb): [10000, '>', '5%']
  __benchmark_pure_training_time(h): [10000, '>', '5%']
  __benchmark_total_time(h): [10000, '>', '5%']
  train.top1_acc: [10000, '<', '5%']

mmaction_slowonly_r50_video_4x16x1_256e_kinetics400_rgb:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '>', '5%']
  __benchmark_mem_alloc(mb): [10000, '>', '5%']
  __benchmark_mem_cached(mb): [10000, '>', '5%']
  __benchmark_pure_training_time(h): [10000, '>', '5%']
  __benchmark_total_time(h): [10000, '>', '5%']
  train.top1_acc: [10000, '<', '5%']

mmaction_tsm_r50_video_1x1x8_100e_kinetics400_rgb:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '>', '5%']
  __benchmark_mem_alloc(mb): [10000, '>', '5%']
  __benchmark_mem_cached(mb): [10000, '>', '5%']
  __benchmark_pure_training_time(h): [10000, '>', '5%']
  __benchmark_total_time(h): [10000, '>', '5%']
  train.top1_acc: [10000, '<', '5%']

mmaction_tsn_r50_video_1x1x8_100e_kinetics400_rgb:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '>', '5%']
  __benchmark_mem_alloc(mb): [10000, '>', '5%']
  __benchmark_mem_cached(mb): [10000, '>', '5%']
  __benchmark_pure_training_time(h): [10000, '>', '5%']
  __benchmark_total_time(h): [10000, '>', '5%']
  train.top1_acc: [10000, '<', '5%']

mmaction_bmn_400x100_2x8_9e_activitynet_feature:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '>', '5%']
  __benchmark_mem_alloc(mb): [10000, '>', '5%']
  __benchmark_mem_cached(mb): [10000, '>', '5%']
  __benchmark_pure_training_time(h): [10000, '>', '5%']
  __benchmark_total_time(h): [10000, '>', '5%']
  train.auc: [10000, '<', '5%']
  train.AR@100: [10000, '<', '5%']

# benchmark
mmaction_i3d_r50_video_32x2x1_100e_kinetics400_rgb.benchmark:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '>', '5%']
  __benchmark_mem_alloc(mb): [10000, '>', '5%']
  __benchmark_mem_cached(mb): [10000, '>', '5%']
  __benchmark_pure_training_time(h): [10000, '>', '5%']
  __benchmark_total_time(h): [10000, '>', '5%']

mmaction_r2plus1d_r34_video_8x8x1_180e_kinetics400_rgb.benchmark:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '>', '5%']
  __benchmark_mem_alloc(mb): [10000, '>', '5%']
  __benchmark_mem_cached(mb): [10000, '>', '5%']
  __benchmark_pure_training_time(h): [10000, '>', '5%']
  __benchmark_total_time(h): [10000, '>', '5%']

mmaction_slowfast_r50_video_4x16x1_256e_kinetics400_rgb.benchmark:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '>', '5%']
  __benchmark_mem_alloc(mb): [10000, '>', '5%']
  __benchmark_mem_cached(mb): [10000, '>', '5%']
  __benchmark_pure_training_time(h): [10000, '>', '5%']
  __benchmark_total_time(h): [10000, '>', '5%']

mmaction_slowonly_r50_video_4x16x1_256e_kinetics400_rgb.benchmark:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '>', '5%']
  __benchmark_mem_alloc(mb): [10000, '>', '5%']
  __benchmark_mem_cached(mb): [10000, '>', '5%']
  __benchmark_pure_training_time(h): [10000, '>', '5%']
  __benchmark_total_time(h): [10000, '>', '5%']

mmaction_tsm_r50_video_1x1x8_100e_kinetics400_rgb.benchmark:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '>', '5%']
  __benchmark_mem_alloc(mb): [10000, '>', '5%']
  __benchmark_mem_cached(mb): [10000, '>', '5%']
  __benchmark_pure_training_time(h): [10000, '>', '5%']
  __benchmark_total_time(h): [10000, '>', '5%']

mmaction_tsn_r50_video_1x1x8_100e_kinetics400_rgb.benchmark:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '>', '5%']
  __benchmark_mem_alloc(mb): [10000, '>', '5%']
  __benchmark_mem_cached(mb): [10000, '>', '5%']
  __benchmark_pure_training_time(h): [10000, '>', '5%']
  __benchmark_total_time(h): [10000, '>', '5%']

mmaction_bmn_400x100_2x8_9e_activitynet_feature.benchmark:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '>', '5%']
  __benchmark_mem_alloc(mb): [10000, '>', '5%']
  __benchmark_mem_cached(mb): [10000, '>', '5%']
  __benchmark_pure_training_time(h): [10000, '>', '5%']
  __benchmark_total_time(h): [10000, '>', '5%']