mmaction_i3d_r50_video_32x2x1_100e_kinetics400_rgb:
  # attr: [thresh, has_to_higher/has_to_lower]
  train.top1_acc: [10000, '>', '20%']

mmaction_r2plus1d_r34_video_8x8x1_180e_kinetics400_rgb:
  # attr: [thresh, has_to_higher/has_to_lower]
  train.top1_acc: [10000, '>', '20%']

mmaction_slowfast_r50_video_4x16x1_256e_kinetics400_rgb:
  # attr: [thresh, has_to_higher/has_to_lower]
  train.top1_acc: [10000, '>', '20%']

mmaction_slowonly_r50_video_4x16x1_256e_kinetics400_rgb:
  # attr: [thresh, has_to_higher/has_to_lower]
  train.top1_acc: [10000, '>', '20%']

mmaction_tsm_r50_video_1x1x8_100e_kinetics400_rgb:
  # attr: [thresh, has_to_higher/has_to_lower]
  train.top1_acc: [10000, '>', '20%']

mmaction_tsn_r50_video_1x1x8_100e_kinetics400_rgb:
  # attr: [thresh, has_to_higher/has_to_lower]
  train.top1_acc: [10000, '>', '20%']

mmaction_bmn_400x100_2x8_9e_activitynet_feature:
  # attr: [thresh, has_to_higher/has_to_lower]
  train.auc: [10000, '>', '20%']
  train.AR@100: [10000, '>', '20%']