mmdet_mask_rcnn_r50_caffe_fpn_mstrain_1x_coco: # Required. {framework}_{model}
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, 'has_to_lower']
  __benchmark_mem_alloc(mb): [10000, 'has_to_lower'] 
  __benchmark_mem_cached(mb): [10000, 'has_to_lower']
  __benchmark_pure_training_time(h): [10000, 'has_to_lower']
  __benchmark_total_time(h): [10000, 'has_to_lower']
  train.bbox_mAP_50: [10000, 'has_to_higher']
  train.segm_mAP_50: [10000, 'has_to_higher']

mmdet_mask_rcnn_r50_caffe_fpn_mstrain_1x_coco.benchmark: # Required. {framework}_{model}
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, 'has_to_lower']
  __benchmark_mem_alloc(mb): [10000, 'has_to_lower'] 
  __benchmark_mem_cached(mb): [10000, 'has_to_lower']
  __benchmark_pure_training_time(h): [10000, 'has_to_lower']
  __benchmark_total_time(h): [10000, 'has_to_lower']
  train.bbox_mAP_50: [10000, 'has_to_higher']
  train.segm_mAP_50: [10000, 'has_to_higher']
