mmdet_mask_rcnn_r50_caffe_fpn_mstrain_1x_coco: # Required. {framework}_{model}
  # attr: [thresh, has_to_higher/has_to_lower]
  train.bbox_mAP_50: [10000, '>', '50%']

mmdet_mask_rcnn_r50_caffe_fpn_mstrain_1x_coco.benchmark: # Required. {framework}_{model}
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

mmdet_mask_rcnn_r50_fpn_1x_coco: # Required. {framework}_{model}
  # attr: [thresh, has_to_higher/has_to_lower]
  train.bbox_mAP_50: [10000, '>', '50%']
  train.segm_mAP_50: [10000, '>', '50%']

mmdet_mask_rcnn_r50_fpn_1x_coco.benchmark: # Required. {framework}_{model}
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

mmdet_mask_rcnn_r50_fpn_1x_coco.short: # Required. {framework}_{model}
  # attr: [thresh, has_to_higher/has_to_lower]
  train.bbox_mAP_50: [10000, '>', '50%']
  train.segm_mAP_50: [10000, '>', '50%']

mmdet_cascade_rcnn_r50_fpn_1x_coco: # Required. {framework}_{model}
  # attr: [thresh, has_to_higher/has_to_lower]
  train.bbox_mAP_50: [10000, '>', '50%']

mmdet_cascade_rcnn_r50_fpn_1x_coco.benchmark: # Required. {framework}_{model}
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

mmdet_retinanet_r50_fpn_1x_coco: # Required. {framework}_{model}
  # attr: [thresh, has_to_higher/has_to_lower]
  train.bbox_mAP_50: [10000, '>', '50%']

mmdet_retinanet_r50_fpn_1x_coco.benchmark: # Required. {framework}_{model}
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

mmdet_mask_rcnn_r50_fpn_fp16_1x_coco: # Required. {framework}_{model}
  # attr: [thresh, has_to_higher/has_to_lower]
  train.bbox_mAP_50: [10000, '>', '50%']

mmdet_mask_rcnn_r50_fpn_fp16_1x_coco.benchmark: # Required. {framework}_{model}
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

mmdet_ssd300_coco: # Required. {framework}_{model}
  # attr: [thresh, has_to_higher/has_to_lower]
  train.bbox_mAP_50: [10000, '>', '50%']

mmdet_ssd300_coco.benchmark: # Required. {framework}_{model}
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

mmdet_faster_rcnn_r50_fpn_fp16_1x_coco: # Required. {framework}_{model}
  # attr: [thresh, has_to_higher/has_to_lower]
  train.bbox_mAP_50: [10000, '>', '50%']

mmdet_faster_rcnn_r50_fpn_fp16_1x_coco.benchmark: # Required. {framework}_{model}
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'
