mmediting_cyclegan_lsgan_id0_resnet_in_1x1_246200_summer2winter:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']
  train.val_saved_number: [10000, '<', '50%']

mmediting_deepfillv2_256x256_8x2_celeba:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']
  train.l1: [10000, '>', '50%']

mmediting_dim_stage2_v16_pln_1x1_1000k_comp1k:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']
  train.CONN: [10000, '>', '50%']
  train.GRAD: [10000, '>', '50%']

mmediting_edsr_x2c64b16_g1_300k_div2k:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']
  train.PSNR: [10000, '<', '50%']

mmediting_edvrm_wotsa_x4_g8_600k_reds:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']
  train.PSNR: [10000, '<', '50%']

mmediting_esrgan_psnr_x4c64b23g32_g1_1000k_div2k:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']
  train.PSNR: [10000, '<', '50%']
  train.SSIM: [10000, '<', '50%']

mmediting_gl_256x256_8x12_celeba:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']
  train.l1: [10000, '>', '50%']

mmediting_indexnet_mobv2_1x16_78k_comp1k:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']
  train.CONN: [10000, '>', '50%']
  train.GRAD: [10000, '>', '50%']

mmediting_msrresnet_x4c64b16_g1_1000k_div2k:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']
  train.PSNR: [10000, '<', '50%']
  train.SSIM: [10000, '<', '50%']

mmediting_pconv_256x256_stage1_8x1_celeba:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']
  train.l1: [10000, '>', '50%']

mmediting_pix2pix_vanilla_unet_bn_1x1_80k_facades:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']
  train.val_saved_number: [10000, '<', '50%']

mmediting_srcnn_x4k915_g1_1000k_div2k:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']
  train.PSNR: [10000, '<', '50%']
  train.SSIM: [10000, '<', '50%']

# benchmark
mmediting_cyclegan_lsgan_id0_resnet_in_1x1_246200_summer2winter.benchmark:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']

mmediting_deepfillv2_256x256_8x2_celeba.benchmark:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']

mmediting_dim_stage2_v16_pln_1x1_1000k_comp1k.benchmark:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']

mmediting_edsr_x2c64b16_g1_300k_div2k.benchmark:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']

mmediting_edvrm_wotsa_x4_g8_600k_reds.benchmark:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']

mmediting_esrgan_psnr_x4c64b23g32_g1_1000k_div2k.benchmark:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']

mmediting_gl_256x256_8x12_celeba.benchmark:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']

mmediting_indexnet_mobv2_1x16_78k_comp1k.benchmark:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']

mmediting_msrresnet_x4c64b16_g1_1000k_div2k.benchmark:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']

mmediting_pconv_256x256_stage1_8x1_celeba.benchmark:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']

mmediting_pix2pix_vanilla_unet_bn_1x1_80k_facades.benchmark:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']

mmediting_srcnn_x4k915_g1_1000k_div2k.benchmark:
  # attr: [thresh, </>]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']