mmocr_panet_r18_fpem_ffm_sbn_1x_ctw1500:
  placeholder: none

mmocr_panet_r18_fpem_ffm_sbn_1x_icdar2015:
  placeholder: none

mmocr_psenet_r50_fpnf_sbn_1x_icdar2015:
  placeholder: none
  
mmocr_psenet_r50_fpnf_sbn_1x_ctw1500:
  placeholder: none
