mmpose_topdown_res50:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '<', '50%']
  __benchmark_mem_alloc(mb): [10000, '<', '50%']
  __benchmark_mem_cached(mb): [10000, '<', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '<', '50%']
  train.AP: [0, '>', '50%']
mmpose_topdown_alexnet:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '<', '50%']
  __benchmark_mem_alloc(mb): [10000, '<', '50%']
  __benchmark_mem_cached(mb): [10000, '<', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '<', '50%']
  train.AP: [0, '>', '50%']
mmpose_bottomup_hrnet:
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '<', '50%']
  __benchmark_mem_alloc(mb): [10000, '<', '50%']
  __benchmark_mem_cached(mb): [10000, '<', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '<', '50%']
  train.AP: [0, '>', '50%']
