mmpose_topdown_res50:
  train.AP: [0, '>', '50%', 0.714]
mmpose_topdown_senet50:
  train.AP: [0, '>', '50%', 0.724]
mmpose_topdown_scnet:
  train.AP: [0, '>', '50%', 0.726]
mmpose_topdown_darkpose:
  train.AP: [0, '>', '50%', 0.719]
mmpose_topdown_alexnet:
  train.AP: [0, '>', '50%', 0.396]
mmpose_topdown_hourglass:
  train.AP: [0, '>', '50%', 0.727]
mmpose_topdown_hrnet:
  train.AP: [0, '>', '50%', 0.745]
mmpose_bottomup_hrnet:
  train.AP: [0, '>', '50%', 0.673]
mmpose_topdown_mobilev2:
  train.AP: [0, '>', '50%', 0.640]
mmpose_topdown_shufflev1:
  train.AP: [0, '>', '50%', 0.577]
mmpose_topdown_resnext:
  train.AP: [0, '>', '50%', 0.707]
mmpose_topdown_resnetv1d:
  train.AP: [0, '>', '50%', 0.722]
