nas_lite_proxyless_search: # Required.
  func: nas_lite_func # Required
  args:
    done_flag: "Pipeline is Done"
  thresh: # Required
    iter_speed: 0.53
    prec1: 0.354
    prec5: None

nas_lite_proxyless_search_benchmark: # Required.
  func: nas_lite_func # Required
  args:
    done_flag: "Pipeline is Done"
  thresh: # Required
    iter_speed: 0.53
    prec1: 0.354
    prec5: None