Pattern_attribute_config:
  all:
    __benchmark_avg_iter_time(s):
    - 0.8580275638103485
    - <
    - 5%
    - 0.3467565333843231
    __benchmark_mem_alloc(mb):
    - 1505.7
    - <
    - 5%
    - 1434
    __benchmark_mem_cached(mb):
    - 1529.85
    - <
    - 5%
    - 1457
    __benchmark_pavi_task_id:
    - a84e4d3f-3051-4642-8e40-a1564ccf2162
    __benchmark_pure_training_time(h):
    - 23.20120852974554
    - <
    - 5%
    - 36.919341659877034
    __benchmark_total_time(h):
    - 23.210204126641152
    - <
    - 5%
    - 36.932314549154704
    accuracy_delta_thres-10_age_data_smartphone:
    - 0.7009142441860465
    - '>'
    - 1%
    - 0.7627906976744186
    accuracy_delta_thres-5_age_data_smartphone:
    - 0.45111191860465116
    - '>'
    - 1%
    - 0.5107558139534883
    test_life: 1
Pattern_example_fusion_small_pytorch:
  accuracy_delta_thres-10_age_test_data_student:
  - 0
  - '>'
  - 5%
  accuracy_emotion_test:
  - 0
  - '>'
  - 5%
  accuracy_gender_test_data_ali30w:
  - 0
  - '>'
  - 5%
  all:
    __benchmark_avg_iter_time(s):
    - 0.39355667906999586
    - <
    - 5%
    - 0.3748158848285675
    __benchmark_mem_alloc(mb):
    - 1635.9
    - <
    - 5%
    - 1558
    __benchmark_mem_cached(mb):
    - 3312.75
    - <
    - 5%
    - 3155
    __benchmark_pavi_task_id:
    - 51162ea5-dd47-4241-a428-79481971ecd5
    __benchmark_pure_training_time(h):
    - 31.44998565797011
    - <
    - 5%
    - 29.952367293304867
    __benchmark_total_time(h):
    - 31.459187571545442
    - <
    - 5%
    - 29.961131020519467
    accuracy_delta_thres-10_age_test_data_student:
    - 0.785555
    - '>'
    - 5%
    - 0.8269
    accuracy_emotion_test:
    - 0.9266300000000001
    - '>'
    - 5%
    - 0.9754
    accuracy_gender_test_data_ali30w:
    - 0.80009
    - '>'
    - 5%
    - 0.8422
    test_life: 1
Pattern_eye_best_config_parrots:
  all:
    __benchmark_avg_iter_time(s):
    - 0.059942518472671506
    - <
    - 5%
    - 0.05708811283111572
    __benchmark_mem_alloc(mb):
    - 90.3
    - <
    - 5%
    - 86
    __benchmark_mem_cached(mb):
    - 95.55
    - <
    - 5%
    - 91
    __benchmark_pavi_task_id:
    - a10961c2-076d-467f-a8ae-d11d7b54d63b
    __benchmark_pure_training_time(h):
    - 3.794909994612137
    - <
    - 5%
    - 3.6141999948687022
    __benchmark_total_time(h):
    - 3.799972306251526
    - <
    - 5%
    - 3.619021244049072
    accuracy_open_close_test:
    - 0.9348
    - '>'
    - 0%
    - 0.9348
    accuracy_valid_invalid_test:
    - 0.8729
    - '>'
    - 0%
    - 0.8729
Pattern_gaze_example:
  accuracy_honda3_valid_use_annotation_testset:
  - 10000
  - <
  - 5%
  all:
    __benchmark_avg_iter_time(s):
    - 10000
    - <
    - 5%
    - 0.16
    __benchmark_mem_alloc(mb):
    - 1390.2
    - <
    - 5%
    - 1324
    __benchmark_mem_cached(mb):
    - 1425.9
    - <
    - 5%
    - 1358
    __benchmark_pavi_task_id:
    - ad23654f-20c3-43ac-9f5e-792f33a6b8ff
    __benchmark_pure_training_time(h):
    - 4.980601699173451
    - <
    - 5%
    - 4.7434301896890005
    __benchmark_total_time(h):
    - 4.983785284221172
    - <
    - 5%
    - 4.746462175448736
    accuracy_honda3_valid_use_annotation_testset:
    - 0.5448091350397175
    - <
    - 5%
    - 0.5188658428949691
    angle_gaze_vector:
    - 9.99554366078072
    - '>'
    - 5%
    - 10.521624906084968
    angle_honda3_vector_testset_v3:
    - 10.731634959179571
    - <
    - 5%
    - 10.220604723028163
    test_life: 0
  angle_gaze_vector:
  - 10000
  - '>'
  - 5%
  angle_honda3_vector_testset_v3:
  - 10000
  - <
  - 5%
Pattern_ms1m_arc-resnet100_a-softmax_bs512_mp_parrots:
  average_precision:
  - 0
  - '>'
  - 50%
