Pattern_ms1m_arc-resnet100_a-softmax_bs512_mp_parrots:
    # attr: [thresh, has_to_higher/has_to_lower]
    acc1_ms1m: [0, 'has_to_higher']
    acc5_ms1m: [0, 'has_to_higher']
Pattern_attribute_config:
    # attr: [thresh, has_to_higher/has_to_lower]
    acc1_beard: [0, 'has_to_higher']
    acc1_emotion: [0, 'has_to_higher']
    acc1_eye: [0, 'has_to_higher']
    acc1_face_value: [0, 'has_to_higher']
    acc1_gender: [0, 'has_to_higher']
    acc1_glass: [0, 'has_to_higher']
    acc1_mask: [0, 'has_to_higher']
    acc1_mouth: [0, 'has_to_higher']
    acc1_race: [0, 'has_to_higher']
    acc1_smile: [0, 'has_to_higher']
Pattern_eye_best_config_parrots:
    # attr: [thresh, has_to_higher/has_to_lower]
    acc1_valid_eye_softmax: [0, '<', '50%']
    acc1_eye_softmax: [0, '<','50%']
