Pattern_attribute_config:
  average_precision:
  - 0
  - '>'
  - 50%
Pattern_eye_best_config_parrots:
  all:
    __benchmark_avg_iter_time(s):
    - 0
    - <
    - 50%
    __benchmark_mem_alloc(mb):
    - 0
    - <
    - 50%
    __benchmark_mem_cached(mb):
    - 3108.0
    - <
    - 50%
    __benchmark_pavi_task_id:
    - 9b12e13a-57f0-43d8-bd99-0eef77d9278c
    - 9b12e13a-57f0-43d8-bd99-0eef77d9278c
    __benchmark_pure_training_time(h):
    - 0
    - <
    - 50%
    __benchmark_total_time(h):
    - 0
    - <
    - 50%
    average_precision:
    - 0
    - '>'
    - 50%
Pattern_ms1m_arc-resnet100_a-softmax_bs512_mp_parrots:
  average_precision:
  - 0
  - '>'
  - 50%
