pod-v3.1.0_faster-rcnn-R50-FPN-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod-v3.1.0_faster-rcnn-R50-FPN-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP.5: [0.526, '>', '20%']  # 0.584 - 10%

pod-v3.1.0_faster-rcnn-mobilenet-FPN-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP.5: [0, '>', '20%']

pod-v3.1.0_mask-rcnn-R50-FPN-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP.5: [0.526, '>', '20%']  # 0.592 - 10%

pod-v3.1.0_cascade-rcnn-R50-FPN-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP.5: [0, '>', '20%']

pod-v3.1.0_fcos-R50-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP.5: [0, '>', '20%']

pod-v3.1.0_faster-rcnn-R50-FPN-1x-ms-test-aug: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP.5: [0, '>', '20%']

pod-v3.1.0_effnetd0-bifpn-retina-32epoch: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP.5: [0, '>', '20%']

pod-v3.1.0_faster-rcnn-R50-FPN-cityscapes: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP.5: [0, '>', '20%']

pod-v3.1.0_faster-rcnn-R50-FPN-openimages: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP.5: [0, '>', '20%']

pod-v3.1.0_grid-rcnn-R50-FPN-2x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP.5: [0, '>', '20%']

pod-v3.1.0_keypoint-rcnn-R50-FPN-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP.5: [0, '>', '20%']

pod-v3.1.0_mask-rcnn-R50-FPN-2x-lvis: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP.5: [0, '>', '20%']

pod-v3.1.0_retinanet-R50-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP.5: [0, '>', '20%']

pod-v3.1.0_rfcn-R101-ohem-deform-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP.5: [0, '>', '20%']

pod-v3.1.0_rfcn-shufflenet-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP.5: [0, '>', '20%']

