pod_faster-rcnn-R50-FPN-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_faster-rcnn-R50-FPN-1x_mix: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_retinanet-R50-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_mask-rcnn-R50-FPN-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']
  metrics/segm.AP: [10000, '>', '20%']
  weeklytest:
    __benchmark_avg_iter_time(s):
    - 0.31359564195765127
    - <
    - 50%
    - 0.20906376130510085
    __benchmark_mem_alloc(mb):
    - 11823.0
    - <
    - 50%
    - 7882
    __benchmark_mem_cached(mb):
    - 12120.0
    - <
    - 50%
    - 8080
    __benchmark_pavi_task_id:
    - 6038f047-eaf6-431c-8f35-3e188fd24150
    __benchmark_pure_training_time(h):
    - 0.49209322849909465
    - <
    - 50%
    - 0.3280621523327298
    __benchmark_total_time(h):
    - 12.5
    - <
    - 50%
    - 10.5


pod_mask-rcnn-R50-FPN-1x_mix: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']
  metrics/segm.AP: [10000, '>', '20%']

pod_keypoint-rcnn-R50-FPN-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']
  metrics/keypoints.AP: [10000, '>', '20%']
  weeklytest:
    __benchmark_avg_iter_time(s):
    - 0.31359564195765127
    - <
    - 50%
    - 0.20906376130510085
    __benchmark_mem_alloc(mb):
    - 11823.0
    - <
    - 50%
    - 7882
    __benchmark_mem_cached(mb):
    - 12120.0
    - <
    - 50%
    - 8080
    __benchmark_pavi_task_id:
    - 6038f047-eaf6-431c-8f35-3e188fd24150
    __benchmark_pure_training_time(h):
    - 0.49209322849909465
    - <
    - 50%
    - 0.3280621523327298
    __benchmark_total_time(h):
    - 18
    - <
    - 50%
    - 16


pod_keypoint-rcnn-R50-FPN-1x_mix: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']
  metrics/keypoints.AP: [10000, '>', '20%']

pod_rfcn-R101-ohem-deform-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/mAP0.5: [10000, '>', '20%']
  weeklytest:
    __benchmark_avg_iter_time(s):
    - 0.31359564195765127
    - <
    - 50%
    - 0.20906376130510085
    __benchmark_mem_alloc(mb):
    - 11823.0
    - <
    - 50%
    - 7882
    __benchmark_mem_cached(mb):
    - 12120.0
    - <
    - 50%
    - 8080
    __benchmark_pavi_task_id:
    - 6038f047-eaf6-431c-8f35-3e188fd24150
    __benchmark_pure_training_time(h):
    - 0.49209322849909465
    - <
    - 50%
    - 0.3280621523327298
    __benchmark_total_time(h):
    - 4.2
    - <
    - 50%
    - 2.2


pod_cascade-rcnn-R50-FPN-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']
  weeklytest:
    __benchmark_avg_iter_time(s):
    - 0.31359564195765127
    - <
    - 50%
    - 0.20906376130510085
    __benchmark_mem_alloc(mb):
    - 11823.0
    - <
    - 50%
    - 7882
    __benchmark_mem_cached(mb):
    - 12120.0
    - <
    - 50%
    - 8080
    __benchmark_pavi_task_id:
    - 6038f047-eaf6-431c-8f35-3e188fd24150
    __benchmark_pure_training_time(h):
    - 0.49209322849909465
    - <
    - 50%
    - 0.3280621523327298
    __benchmark_total_time(h):
    - 13.7
    - <
    - 50%
    - 11.7


pod_faster-rcnn-mobilenet-FPN-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_faster-rcnn-mobilenet-FPN-1x_mix: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_faster-rcnn-shufflenet-FPN-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_rfcn-mobilenet-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/mAP0.5: [10000, '>', '20%']
  dailytest:
    __benchmark_avg_iter_time(s):
    - 0.5013178478373159
    - <
    - 5%
    - 0.47744556936887234
    __benchmark_mem_alloc(mb):
    - 2110.5
    - <
    - 5%
    - 2010
    __benchmark_mem_cached(mb):
    - 3061.8
    - <
    - 5%
    - 2916
    __benchmark_pavi_task_id:
    - cc28f98d-5b27-4567-aee7-0502c34cb971
    __benchmark_pure_training_time(h):
    - 0.418336475054423
    - <
    - 5%
    - 0.3984156905280219
    __benchmark_total_time(h):
    - 0.5302990348339082
    - <
    - 5%
    - 0.5050466998418173
    metrics/mAP0.5:
    - 0.19446132999062207
    - '>'
    - 20%
    - 0.24307666248827758

pod_rfcn-shufflenet-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/mAP0.5: [10000, '>', '20%']

pod_grid-rcnn-R50-FPN-2x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']
  weeklytest:
    __benchmark_avg_iter_time(s):
    - 0.31359564195765127
    - <
    - 50%
    - 0.20906376130510085
    __benchmark_mem_alloc(mb):
    - 11823.0
    - <
    - 50%
    - 7882
    __benchmark_mem_cached(mb):
    - 12120.0
    - <
    - 50%
    - 8080
    __benchmark_pavi_task_id:
    - 6038f047-eaf6-431c-8f35-3e188fd24150
    __benchmark_pure_training_time(h):
    - 0.49209322849909465
    - <
    - 50%
    - 0.3280621523327298
    __benchmark_total_time(h):
    - 26.13
    - <
    - 50%
    - 24.13


pod_retinanet-R50-ghm-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_faster-rcnn-R50-FPN-1x-DCN@C3-C5: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_retinanet-R50-GN-FA: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_faster-rcnn-R50-NASFPN-1x_mix: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']
  weeklytest:
    __benchmark_avg_iter_time(s):
    - 0.31359564195765127
    - <
    - 50%
    - 0.20906376130510085
    __benchmark_mem_alloc(mb):
    - 11823.0
    - <
    - 50%
    - 7882
    __benchmark_mem_cached(mb):
    - 12120.0
    - <
    - 50%
    - 8080
    __benchmark_pavi_task_id:
    - 6038f047-eaf6-431c-8f35-3e188fd24150
    __benchmark_pure_training_time(h):
    - 0.49209322849909465
    - <
    - 50%
    - 0.3280621523327298
    __benchmark_total_time(h):
    - 19.6
    - <
    - 50%
    - 17.6


pod_faster-rcnn-R50-PAFPN-1x_mix: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_faster-rcnn-R50-FPN-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_faster-rcnn-R50-FPN-1x_mix.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_retinanet-R50-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_mask-rcnn-R50-FPN-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_mask-rcnn-R50-FPN-1x_mix.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_keypoint-rcnn-R50-FPN-1x.short: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']
  metrics/keypoints.AP: [10000, '>', '20%']
  dailytest:
    __benchmark_avg_iter_time(s):
    - 0.31359564195765127
    - <
    - 50%
    - 0.20906376130510085
    __benchmark_mem_alloc(mb):
    - 11823.0
    - <
    - 50%
    - 7882
    __benchmark_mem_cached(mb):
    - 12120.0
    - <
    - 50%
    - 8080
    __benchmark_pavi_task_id:
    - 6038f047-eaf6-431c-8f35-3e188fd24150
    __benchmark_pure_training_time(h):
    - 0.49209322849909465
    - <
    - 50%
    - 0.3280621523327298
    __benchmark_total_time(h):
    - 1.019
    - <
    - 50%
    - 0.519
    metrics/bbox.AP:
    - 0.19446132999062207
    - '>'
    - 20%
    - 0.24307666248827758
    metrics/keypoints.AP:
    - 0.19446132999062207
    - '>'
    - 20%
    - 0.24307666248827758


pod_keypoint-rcnn-R50-FPN-1x.short.dummy_data: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_keypoint-rcnn-R50-FPN-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_keypoint-rcnn-R50-FPN-1x_mix.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_rfcn-R101-ohem-deform-1x.short: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/mAP0.5: [10000, '>', '20%']

pod_rfcn-R101-ohem-deform-1x.short.dummy_data: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_rfcn-R101-ohem-deform-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_cascade-rcnn-R50-FPN-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_faster-rcnn-mobilenet-FPN-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_faster-rcnn-mobilenet-FPN-1x_mix.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_faster-rcnn-shufflenet-FPN-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_rfcn-mobilenet-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_rfcn-shufflenet-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_grid-rcnn-R50-FPN-2x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_retinanet-R50-ghm-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_faster-rcnn-R50-FPN-1x-DCN@C3-C5.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_retinanet-R50-GN-FA.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_faster-rcnn-R50-NASFPN-1x_mix.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_faster-rcnn-R50-PAFPN-1x_mix.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_faster-rcnn-R50-C4-1x.short: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']
  dailytest:
    __benchmark_avg_iter_time(s):
    - 0.31359564195765127
    - <
    - 50%
    - 0.20906376130510085
    __benchmark_mem_alloc(mb):
    - 11823.0
    - <
    - 50%
    - 7882
    __benchmark_mem_cached(mb):
    - 12120.0
    - <
    - 50%
    - 8080
    __benchmark_pavi_task_id:
    - 6038f047-eaf6-431c-8f35-3e188fd24150
    __benchmark_pure_training_time(h):
    - 0.49209322849909465
    - <
    - 50%
    - 0.3280621523327298
    __benchmark_total_time(h):
    - 1.025
    - <
    - 50%
    - 0.525
    metrics/bbox.AP:
    - 0.19446132999062207
    - '>'
    - 20%
    - 0.24307666248827758


pod_faster-rcnn-R50-C4-1x.short.dummy_data: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_faster-rcnn-R50-C4-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'
