pod_faster-rcnn-R50-FPN-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/bbox.AP: 0.5

pod_faster-rcnn-R50-FPN-1x_mix: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/bbox.AP: 0.5

pod_retinanet-R50-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/bbox.AP: 0.5

pod_mask-rcnn-R50-FPN-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/bbox.AP: 0.5
  metrics/segm.AP: 0.5

pod_mask-rcnn-R50-FPN-1x_mix: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/bbox.AP: 0.5
  metrics/segm.AP: 0.5

pod_keypoint-rcnn-R50-FPN-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/bbox.AP: 0.5
  metrics/keypoints.AP: 0.5

pod_keypoint-rcnn-R50-FPN-1x_mix: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/bbox.AP: 0.5
  metrics/keypoints.AP: 0.5

pod_rfcn-R101-ohem-deform-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/mAP0.5: 0.5

pod_cascade-rcnn-R50-FPN-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/bbox.AP: 0.5

pod_faster-rcnn-mobilenet-FPN-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/bbox.AP: 0.5

pod_faster-rcnn-mobilenet-FPN-1x_mix: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/bbox.AP: 0.5

pod_faster-rcnn-shufflenet-FPN-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/bbox.AP: 0.5

pod_rfcn-mobilenet-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/mAP0.5: 0.5

pod_rfcn-shufflenet-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/mAP0.5: 0.5

pod_grid-rcnn-R50-FPN-2x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/bbox.AP: 0.5

pod_retinanet-R50-ghm-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/bbox.AP: 0.5

pod_faster-rcnn-R50-FPN-1x-DCN@C3-C5: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/bbox.AP: 0.5

pod_retinanet-R50-GN-FA: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/bbox.AP: 0.5

pod_faster-rcnn-R50-NASFPN-1x_mix: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/bbox.AP: 0.5

pod_faster-rcnn-R50-PAFPN-1x_mix: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/bbox.AP: 0.5

pod_faster-rcnn-R50-FPN-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']

pod_faster-rcnn-R50-FPN-1x_mix.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']

pod_retinanet-R50-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']

pod_mask-rcnn-R50-FPN-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']

pod_mask-rcnn-R50-FPN-1x_mix.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']

pod_keypoint-rcnn-R50-FPN-1x.short: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/bbox.AP: 0.5
  metrics/keypoints.AP: 0.5

pod_keypoint-rcnn-R50-FPN-1x.short.dummy_data: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/bbox.AP: 0.5
  metrics/keypoints.AP: 0.5

pod_keypoint-rcnn-R50-FPN-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']

pod_keypoint-rcnn-R50-FPN-1x_mix.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']

pod_rfcn-R101-ohem-deform-1x.short: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/mAP0.5: 0.5

pod_rfcn-R101-ohem-deform-1x.short.dummy_data: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/mAP0.5: 0.5

pod_rfcn-R101-ohem-deform-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']

pod_cascade-rcnn-R50-FPN-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']

pod_faster-rcnn-mobilenet-FPN-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']

pod_faster-rcnn-mobilenet-FPN-1x_mix.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']

pod_faster-rcnn-shufflenet-FPN-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']

pod_rfcn-mobilenet-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']

pod_rfcn-shufflenet-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']

pod_grid-rcnn-R50-FPN-2x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']

pod_retinanet-R50-ghm-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']

pod_faster-rcnn-R50-FPN-1x-DCN@C3-C5.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']

pod_retinanet-R50-GN-FA.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']

pod_faster-rcnn-R50-NASFPN-1x_mix.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']

pod_faster-rcnn-R50-PAFPN-1x_mix.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']

pod_faster-rcnn-R50-C4-1x.short: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/bbox.AP: 0.5

pod_faster-rcnn-R50-C4-1x.short.dummy_data: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
  metrics/bbox.AP: 0.5

pod_faster-rcnn-R50-C4-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [0.8, 'has_to_lower']
  __benchmark_mem_alloc(mb): [8000, 'has_to_lower']
  __benchmark_mem_cached(mb): [5000, 'has_to_lower']
  __benchmark_pure_training_time(h): [1.5, 'has_to_lower']
  __benchmark_total_time(h): [2, 'has_to_lower']
