pod_faster-rcnn-R50-FPN-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_faster-rcnn-R50-FPN-1x_mix: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_retinanet-R50-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_mask-rcnn-R50-FPN-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']
  metrics/segm.AP: [10000, '>', '20%']

pod_mask-rcnn-R50-FPN-1x_mix: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']
  metrics/segm.AP: [10000, '>', '20%']

pod_keypoint-rcnn-R50-FPN-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']
  metrics/keypoints.AP: [10000, '>', '20%']

pod_keypoint-rcnn-R50-FPN-1x_mix: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']
  metrics/keypoints.AP: [10000, '>', '20%']

pod_rfcn-R101-ohem-deform-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/mAP0.5: [10000, '>', '20%']

pod_cascade-rcnn-R50-FPN-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_faster-rcnn-mobilenet-FPN-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_faster-rcnn-mobilenet-FPN-1x_mix: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_faster-rcnn-shufflenet-FPN-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_rfcn-mobilenet-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/mAP0.5: [10000, '>', '20%']

pod_rfcn-shufflenet-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/mAP0.5: [10000, '>', '20%']

pod_grid-rcnn-R50-FPN-2x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_retinanet-R50-ghm-1x: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_faster-rcnn-R50-FPN-1x-DCN@C3-C5: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_retinanet-R50-GN-FA: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_faster-rcnn-R50-NASFPN-1x_mix: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_faster-rcnn-R50-PAFPN-1x_mix: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_faster-rcnn-R50-FPN-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_faster-rcnn-R50-FPN-1x_mix.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_retinanet-R50-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_mask-rcnn-R50-FPN-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_mask-rcnn-R50-FPN-1x_mix.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_keypoint-rcnn-R50-FPN-1x.short: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']
  metrics/keypoints.AP: [10000, '>', '20%']

pod_keypoint-rcnn-R50-FPN-1x.short.dummy_data: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_keypoint-rcnn-R50-FPN-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_keypoint-rcnn-R50-FPN-1x_mix.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_rfcn-R101-ohem-deform-1x.short: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/mAP0.5: [10000, '>', '20%']

pod_rfcn-R101-ohem-deform-1x.short.dummy_data: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_rfcn-R101-ohem-deform-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_cascade-rcnn-R50-FPN-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_faster-rcnn-mobilenet-FPN-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_faster-rcnn-mobilenet-FPN-1x_mix.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_faster-rcnn-shufflenet-FPN-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_rfcn-mobilenet-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_rfcn-shufflenet-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_grid-rcnn-R50-FPN-2x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_retinanet-R50-ghm-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_faster-rcnn-R50-FPN-1x-DCN@C3-C5.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_retinanet-R50-GN-FA.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_faster-rcnn-R50-NASFPN-1x_mix.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_faster-rcnn-R50-PAFPN-1x_mix.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_faster-rcnn-R50-C4-1x.short: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/bbox.AP: [10000, '>', '20%']

pod_faster-rcnn-R50-C4-1x.short.dummy_data: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

pod_faster-rcnn-R50-C4-1x.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'
