pod_v2.3.0_retinanet-v11-18w: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/mAP:0.35: [10000, '>', '20%', 0.369]

pod_v2.3.0_fcos-v11-80w-stride4: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  metrics/mAP:0.5: [10000, '>', '20%', 0.508]
