pod_v2.3.0_retinanet-v11-18w: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']
  metrics/mAP:0.35: [10000, '<', '50%']

pod_v2.3.0_fcos-v11-80w-stride4: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']
  metrics/mAP:0.5: [10000, '<', '50%']
