seg_pspnet: # Required. {framework}_{model}
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%'] 
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']
  eval_mIoU: [10000, '<', '50%']
seg_deeplab: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']
  eval_mIoU: [10000, '<', '50%']
seg_mobilenet_v2_plus: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']
  mIoU: [10000, '<', '50%']

seg_pspnet.benchmark: # Required. {framework}_{model}
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%'] 
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']
  eval_mIoU: [10000, '<', '50%']
seg_deeplab.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']
  eval_mIoU: [10000, '<', '50%']
seg_mobilenet_v2_plus.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']
  mIoU: [10000, '<', '50%']
