seg_pspnet: # Required. {framework}_{model}
  # attr: [thresh, has_to_higher/has_to_lower]
  eval_mIoU: [10000, '>', '20%']

seg_deeplab: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  eval_mIoU: [10000, '>', '20%']

seg_mobilenet_v2_plus: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  mIoU: [10000, '>', '20%']

seg_pspnet.benchmark: # Required. {framework}_{model}
  # attr: [thresh, has_to_higher/has_to_lower]
  eval_mIoU: [10000, '>', '20%']

seg_deeplab.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

seg_mobilenet_v2_plus.benchmark: # Required.
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'
