seg_nas_single_path_oneshot: # Required
  # attr: [thresh, '>/<', '0.50%/1', val1, val2, ...]
  test_acc: [10000, '>', '20%']

seg_nas_single_path_oneshot_benchmark: # Required
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'
