seg_nas_single_path_oneshot: # Required
  # attr: [thresh, '>/<', '0.50%/1', val1, val2, ...]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']
  test_acc: [10000, '<', '50%']

seg_nas_single_path_oneshot_benchmark: # Required
  # attr: [thresh, has_to_higher/has_to_lower]
  __benchmark_avg_iter_time(s): [10000, '>', '50%']
  __benchmark_mem_alloc(mb): [10000, '>', '50%']
  __benchmark_mem_cached(mb): [10000, '>', '50%']
  __benchmark_pure_training_time(h): [10000, '>', '50%']
  __benchmark_total_time(h): [10000, '>', '50%']
