ssd_ssd_FSAF: # Required
  func: ssd_func
  args:
    done_flag: "Pipeline is Done"
  thresh: # Required
    total_time: 16.0
    iter_speed: 0.860
    valid_top1: 0.3737
ssd_ssd_Retina:
  func: ssd_func
  args:
    done_flag: "Pipeline is Done"
  thresh: # Required
    total_time: 12.0
    iter_speed: 0.700
    valid_top1: 0.3450
