ssd_ssd_FSAF: # Required
  # attr: [thresh, has_to_higher/has_to_lower]
  epoch/mAP: [10000, '>', '20%']

ssd_ssd_Retina:
  # attr: [thresh, has_to_higher/has_to_lower]
  epoch/mAP: [10000, '>', '20%']

ssd_ssd_FSAF_benchmark: # Required
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'

ssd_ssd_Retina_benchmark:
  # attr: [thresh, has_to_higher/has_to_lower]
  placeholder: 'none'
