star_topdown_resnet50:
  __benchmark_avg_iter_time(s): [2.273, '>', '50%'] # 1.894 x 1.2
  __benchmark_mem_alloc(mb): [31125, '>', '50%'] # 25938 x 1.2
  __benchmark_mem_cached(mb): [36405, '>', '50%'] # 30338 x 1.2
  __benchmark_pure_training_time(h): [100000, '>', '50%']
  __benchmark_total_time(h): [100000, '>', '50%']
  Train_Accuracy: [0, '<', '50%']
star_topdown_resnest50:
  __benchmark_avg_iter_time(s): [1.2864, '>', '50%'] # 1.072 x 1.2
  __benchmark_mem_alloc(mb): [22459, '>', '50%'] # 18716 x 1.2
  __benchmark_mem_cached(mb): [26188, '>', '50%'] # 21824 x 1.2
  __benchmark_pure_training_time(h): [100000, '>', '50%']
  __benchmark_total_time(h): [100000, '>', '50%']
  Train_Accuracy: [0, '<', '50%']
star_topdown_jnet:
  __benchmark_avg_iter_time(s): [1.210, '>', '50%'] # 1.009 x 1.2
  __benchmark_mem_alloc(mb): [5443, '>', '50%'] # 4536 x 1.2
  __benchmark_mem_cached(mb): [6868, '>', '50%'] # 5724 x 1.2
  __benchmark_pure_training_time(h): [100000, '>', '50%']
  __benchmark_total_time(h): [100000, '>', '50%']
  Train_Accuracy: [0, '<', '50%']
star_topdown_hrnet32:
  __benchmark_avg_iter_time(s): [100000, '>', '50%'] # 1.009 x 1.2
  __benchmark_mem_alloc(mb): [100000, '>', '50%'] # 4536 x 1.2
  __benchmark_mem_cached(mb): [100000, '>', '50%'] # 5724 x 1.2
  __benchmark_pure_training_time(h): [100000, '>', '50%']
  __benchmark_total_time(h): [100000, '>', '50%']
  Train_Accuracy: [0, '<', '50%']
star_bottomup_hrnet32:
  __benchmark_avg_iter_time(s): [100000, '>', '50%'] # 1.009 x 1.2
  __benchmark_mem_alloc(mb): [100000, '>', '50%'] # 4536 x 1.2
  __benchmark_mem_cached(mb): [100000, '>', '50%'] # 5724 x 1.2
  __benchmark_pure_training_time(h): [100000, '>', '50%']
  __benchmark_total_time(h): [100000, '>', '50%']
  Train_Accuracy: [0, '<', '50%']
star_bottomup_jnet:
  __benchmark_avg_iter_time(s): [100000, '>', '50%'] # 1.009 x 1.2
  __benchmark_mem_alloc(mb): [100000, '>', '50%'] # 4536 x 1.2
  __benchmark_mem_cached(mb): [100000, '>', '50%'] # 5724 x 1.2
  __benchmark_pure_training_time(h): [100000, '>', '50%']
  __benchmark_total_time(h): [100000, '>', '50%']
  Train_Accuracy: [0, '<', '50%']
