star_topdown_resnet50:
  Train_Accuracy: [0, '>', '20%']

star_topdown_resnest50:
  Train_Accuracy: [0, '>', '20%']

star_topdown_jnet:
  Train_Accuracy: [0, '>', '20%']

star_topdown_hrnet32:
  Train_Accuracy: [0, '>', '20%']

star_bottomup_hrnet32:
  Train_Accuracy: [0, '>', '20%']

star_bottomup_jnet:
  Train_Accuracy: [0, '>', '20%']
