seed: 99
net:
    arch: googlenet
    kwargs:
        num_classes: 1000
        aux_logits: True

dataset:
  train:
    meta_file: /mnt/lustre/share/images/meta/train.txt
    image_dir: /mnt/lustre/share/images/train
    random_resize_crop: 224
    colorjitter: [0.2, 0.2, 0.2, 0.1]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: True
  test:
    meta_file: /mnt/lustre/share/images/meta/val.txt
    image_dir: /mnt/lustre/share/images/val
    resize: 256
    center_crop: [224, 224]
    colorjitter:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: False
  batch_size: 128 #  64 for 4 card
  workers: 6

trainer:
  max_epoch: 150
  test_freq: 1
  log_freq: 200
  optimizer:
    type: SGD
    kwargs:
      lr: 0.5 # 0.1 for 4 card
      momentum: 0.9
      weight_decay: 0.00008 # 0.00004 for 4 card
  lr_scheduler:
    warmup_epochs: 0
    type: StepLR
    kwargs:
      step_size: 30
      gamma: 0.1

saver:
  pretrain_model:
  resume_model:
  save_dir: checkpoints/googlenet   # save checkpoint locally
