seed: 99
net:
    type: inception_v3
    kwargs:
        num_classes: 1000
    #bn:
    #    group_size: 1
    #fp16:
    #    scale_factor: 1024
 
dataset:
  train:
    meta_file: /mnt/lustre/share/images/meta/train.txt
    image_dir: /mnt/lustre/share/images/train
    reader: pillow
    resize: 341
    random_crop: [299, 299]
    colorjitter: [0.2, 0.2, 0.2, 0.1]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: True
  test:
    meta_file: /mnt/lustre/share/images/meta/val.txt
    image_dir: /mnt/lustre/share/images/val
    reader: pillow
    resize: 341
    center_crop: [299, 299]
    colorjitter:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: True
  batch_size: 32
  workers: 4
 
trainer:
  max_epoch: 120
  test_freq: 120
  log_freq: 100
  label_smooth:
  optimizer:
    type: SGD
    kwargs:
      lr: 0.2
      momentum: 0.9
      weight_decay: 0.0001
  lr_scheduler:
    warmup_epochs: 0
    type: CosineLR
    kwargs:
      min_lr: 0.0
 
saver:
  #pretrian_model: /mnt/lustre/share/DSK/model_zoo/pytorch/imagenet/resnet50-19c8e357.pth
  #resume_model: ckpt_e1.pth_02c603a7-3959-4b58-b089-723e39f75974
  #load_pavi:    # load pretrain/resume model from pavi
  #save_pavi:    # add snapshot to pavi
  save_dir: checkpoints/inceptionv3   # save checkpoint locally
  save_epoch_freq: 120
  save_latest: True
  save_best: True
  sync_bn_stats: False  
 
monitor:
  # type: pavi
  # kwargs:
  #   project: zhujuan_demo
  #   task: inception_v3
  #   model: inception_v3
  # type: tensorboard
  # kwargs:
  #     logdir: tensorboard
