seed: 99
net:
    arch: shuffle_v1
    kwargs:
        num_classes: 1000
        groups: 3
        in_channels: 3
        width_mult: 1
 
dataset:
  train:
    meta_file: /mnt/lustre/share/images/meta/train.txt
    image_dir: /mnt/lustre/share/images/train
    reader: pillow
    random_resize_crop: 224
    colorjitter: [0.2, 0.2, 0.2, 0.1]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: True
  test:
    meta_file: /mnt/lustre/share/images/meta/val.txt
    image_dir: /mnt/lustre/share/images/val
    reader: pillow
    resize: 256
    center_crop: [224, 224]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: False
  batch_size: 32
  workers: 4
 
trainer:
  max_epoch: 1
  test_freq: 2
  log_freq: 100
  label_smooth:
  optimizer:
    type: SGD
    kwargs:
      lr: 0.12
      momentum: 0.9
      weight_decay: 0.00004
  lr_scheduler:
    warmup_epochs: 0
    type: MultiStepLR
    kwargs:
      milestones: [30,60,90]
      gamma: 0.1
 
saver:
  # pretrian_model: 
  # resume_model: 
  # load_pavi:   # load pretrain/resume model from pavi
  # save_pavi: True   # add snapshot to pavi
  save_dir: checkpoints/shuffle_v1   # save checkpoint locally
  save_epoch_freq: 1
  save_latest: False
  save_best: False
 
# monitor:
  # type: pavi
  # kwargs:
    # project: default
    # task: shuffle_v1_1x
    # model: shuffle_v1_1x
  # type: tensorboard
  # kwargs:
  #     logdir: tensorboard
