augment: randaugmentmixupN${RA.N}M${RA.M}A${RA.A}
RA:
    N: 2
    M: 9
    A: 0.2
data:
    origin_train:
        transform_image:
            name: TrainRandAugment
            num_ops: '@{RA.N}'
            magnitude_level: '@{RA.M}'
        transform_batch:
            name: cuda_remain_mixup
            alpha: '@{RA.A}'
            keepleft: true
    nas_train:
        transform_image:
            name: TrainRandAugment
            num_ops: '@{RA.N}'
            magnitude_level: '@{RA.M}'
        transform_batch:
            name: cuda_remain_mixup
            alpha: '@{RA.A}'
            keepleft: true
    adabn:
        transform_image:
            name: TrainRandAugment
            num_ops: '@{RA.N}'
            magnitude_level: '@{RA.M}'
        transform_batch:
            name: cuda_remain_mixup
            alpha: '@{RA.A}'
            keepleft: true
