py_file: coarse_multiple_search.py
run_name: ${project}/coarse_multiple_search/${common_setting}_${search_name}_${resource_type}
num_epochs: '@{all_num_epochs.super_learn}'
ckpt: ''
resource_type: flops
critical_metric_name: top1
critical_metric_polar: max
search_name: nas_valid
report_name: origin_valid
figsize: [8, 6]
plot_log_scale: false
data:
    names: [adabn, nas_valid, origin_valid]
network:
    main:
        init: ckpt
        ckpt: '@{ckpt}'
metric:
    names: [nas_valid, origin_valid]
    nas_valid: '@{metric.valid}'
    origin_valid: '@{metric.valid}'
coarse_combine_jump_dict:
    resolution: 1
    grouch: 1
    groups: 1
    kernel_size: 1
    num_blocks: 1
    out_channels: 1
