run_names:
    super_learn: ${project}/super_learn/${se_prefix}mobilenet_v2_${width}_${augment}_${range_and_round}/gpu32_subgroup4_epoch${num_epochs}
    evolve: ${project}/evolve/${se_prefix}mobilenet_v2_${width}_${augment}_${range_and_round}/gpu32_subgroup4_epoch${num_epochs}/flops
    rand_eval_hist: ${project}/rand_eval_hist/${se_prefix}mobilenet_v2_${width}_${augment}_${range_and_round}/gpu32_subgroup4_epoch${num_epochs}
    normal_learn: ${project}/normal_learn/${se_prefix}mobilenet_v2_${width}_${augment}_${range_and_round}/gpu32_subgroup4_epoch${num_epochs}
    show_axis_dist:  ${project}/show_axis_dist/${se_prefix}mobilenet_v2_${width}_${augment}_${range_and_round}/gpu32_subgroup4_epoch${num_epochs}

num_gpus: 32
lr: 0.4
num_epochs: 200
subnet_num_groups: 4
evolve_ckpt: ''
eval_ckpt: ''

network:
    std:
        name: super_mobilenet_v2
        kwargs:
            search_space_path: '@{std_search_space_path}'
            zero_gamma: false
            num_classes: '@{num_classes}'
            seed: '@{seed}'
        init: default
        ckpt: null
    main:
        name: super_mobilenet_v2
        kwargs:
            search_space_path: '@{search_space_path}'
            zero_gamma: false
            num_classes: '@{num_classes}'
            seed: '@{seed}'
        init: default
        ckpt: null

super_net_name: mobilenet_v2
std_search_space_path: configs/outcome/${se_prefix}mobilenet_v2_${width}_standard.yaml
search_space_path: configs/alphatrion_nas/search/${se_prefix}mobilenet_v2_${width}_${augment}_${range_and_round}.yaml
outcome_path: configs/outcome/${se_prefix}mobilenet_v2_${width}_${augment}_${range_and_round}.yaml

optimizer:
    main:
        kwargs:
            weight_decay: 0.00004
