py_file: refine_multiple_search.py
# run_name: ${project}/refine_multiple_search/${common_setting}_${search_name}_${resource_type}_walk${max_walk_steps}
run_name: ${project}/refine_multiple_search/${common_setting}_${search_name}_${resource_type}_mag${max_magnitude}
num_epochs: 100
ckpt: ''
coarse_ckpt: ''
resource_type: flops
critical_metric_name: top1
critical_metric_polar: max
search_name: nas_valid
report_name: origin_valid
figsize: [8, 6]
refine_parent: true
max_walk_steps: 1.0
max_magnitude: 0.5
plot_log_scale: false
data:
    names: [adabn, nas_valid, origin_valid]
network:
    main:
        init: ckpt
        ckpt: '@{ckpt}'
metric:
    names: [nas_valid, origin_valid]
    nas_valid: '@{metric.valid}'
    origin_valid: '@{metric.valid}'
