py_file: super_learn.py
run_name: ${project}/super_learn/${common_setting}_full_train
num_epochs: '@{all_num_epochs.super_learn}'
eval_names: [max_nas_valid, min_nas_valid, max_origin_valid, min_origin_valid]
data:
    names: [train, adabn, max_nas_valid, min_nas_valid, max_origin_valid, min_origin_valid]
    train: '@{data.origin_train}'
    max_nas_valid: '@{data.nas_valid}'
    min_nas_valid: '@{data.nas_valid}'
    max_origin_valid: '@{data.origin_valid}'
    min_origin_valid: '@{data.origin_valid}'
metric:
    names: [train, max_nas_valid, min_nas_valid, max_origin_valid, min_origin_valid]
    max_nas_valid: '@{metric.valid}'
    min_nas_valid: '@{metric.valid}'
    max_origin_valid: '@{metric.valid}'
    min_origin_valid: '@{metric.valid}'
    critical_metric_names: []
