py_file: learn.py
wait_tensorboard: 5
mp_method: spawn
partition: Test
srun_extra_args: ''
gen_run_file: run.sh
pg_run: true

run_name: bag_of_tricks/resnet50/gpu8_batch32_0gamma_nodecay_smooth0.1_mixup0.2_warmup5_coslr0.1_epoch50_fp16
seed: 1024
num_gpus: 8
local_batch_size: 32
lr: 0.1
image_size: 224
num_epochs: 50
num_classes: 1000
num_sub_epochs: 1
resume: ../checkpoint/latest.pth
eval_names: [valid]
data_reader: MemcachedReader   # CephReader
imagenet_train_root: /mnt/lustre/share/images/train  # s3://parrots_data/images/train
imagenet_valid_root: /mnt/lustre/share/images/val  # s3://parrots_data/images/val

mixed:
    use: true
    loss_scale: 512 
    dynamic_scale_init: 4294967296 #(2^32) 
    dynamic_scale_factor: 2. 
    dynamic_scale_window: 1000
    float_bn: True
    #float_module_type: "{torch.nn.Conv2d:('float', 'half')}"
    #float_module_name: "{'fc':('float', 'half')}"
   
data:
    loader_class: alphatrion
    names: [train, valid]
    train:
        imglist_type: ListImglist
        imglist_path: /mnt/lustre/share/images/meta/train.txt
        root: '@{imagenet_train_root}'
        reader: '@{data_reader}'
        skip_broken: false
        dataset_debug_kwargs: 
            maxlen: null
            dummy_read: false
            dummy_size: null
        num_sub_epochs: '@{num_sub_epochs}'
        shuffle: true
        finegrain_factor: 1000
        seed: '@{seed}'
        local_batch_size: '@{local_batch_size}'
        num_workers: 2
        transform_image:
            name: TrainImagenet
            image_size: '@{image_size}'
            partial: false
        transform_extra:
            name: SmoothSingleLabel
            epsilon: 0.1
            num_classes: '@{num_classes}'
        transform_batch:
            name: cuda_remain_mixup
            alpha: 0.2
    valid:
        imglist_type: ListImglist
        imglist_path: /mnt/lustre/share/images/meta/val.txt
        root: '@{imagenet_valid_root}'
        reader: '@{data_reader}'
        skip_broken: false
        dataset_debug_kwargs:
            maxlen: null
            dummy_read: false
            dummy_size: null
        num_sub_epochs: 1
        shuffle: false
        finegrain_factor: 1000
        seed: '@{seed}'
        local_batch_size: '@{local_batch_size}'
        num_workers: '@{data.train.num_workers}'
        transform_image:
            name: ValidImagenet
            image_size: '@{image_size}'
            partial: false
        transform_extra:
            name: SmoothSingleLabel
            epsilon: 0.1
            num_classes: '@{num_classes}'
        transform_batch:
            name: cuda_remain

network:
    names: [main]
    main:
        name: gluon.resnet50_v1d
        kwargs:
            pretrained: false
            zero_gamma: true
            num_classes: '@{num_classes}'
        init: default
        ckpt: null

optimizer:
    names: [main]
    main:
        name: SGD
        kwargs:
            lr: 0 # 交给scheduler控制
            weight_decay: 0.0001
            momentum: 0.9
            nesterov: true
        param_groups: bias_bn_no_decay

scheduler:
    names: [lr]
    lr:
        name: CosineScheduler
        unit_length: epoch
        kwargs:
            base_value: '@{lr}'
            total_steps: '@{num_epochs}'
            warmup_steps: 5

metric:
    names: [train, valid]
    train:
        metric_names: [sce, top1, top5]
        cache_size: 20
    valid:
        metric_names: [sce, top1, top5]
        cache_size: null
    loss: sce
    critical_metric_names: [valid_top1, valid_top5]
    
    speeds:
        sce: fast
        top1: fast
        top5: fast
    polars:
        sce: min
        top1: max
        top5: max
    ruler: ClassifyRuler

record:
    names: [train, eval]
    train:
        window_size: 100
        sync_cuda: false
    eval:
        window_size: 100
        sync_cuda: false

report:
    plain_freq: 10
    curve_freq: 100
    lr_axis_factor: 1000000

pavi:
    use: false
    writer:
        task: '@{run_name}'
        project: 'default'
