data:
  lustre:
    data_dir: /mnt/lustre/share_data/parrots_model_data/coronary_npy
  ceph:
    data_dir: s3://parrots_model_data/coronary_npy
    meta_file: s3://parrots_model_data/coronary_npy/meta_file.txt
