DATA_SAMPLE_INTERVAL: 1

INPUT_DATA:
    PETREL_OSS: ['/mnt/lustre/share_data/', 's3://']
    TRAIN:
        INFO_PATH: "/mnt/lustre/share_data/parrots_model_data/3ddet/internal_18W-PK1-2_int-10_around.pkl"
        DBINFO_PATH: "/mnt/lustre/share_data/parrots_model_data/3ddet/internal_18W-PK1-2_int-10_db_infos_around.pkl"
        MAX_NUMBER_OF_VOXELS: 100000
        SHUFFLE_POINTS: true
    TEST:
        INFO_PATH: "/mnt/lustre/share_data/parrots_model_data/3ddet/hesai_test_20-0113/hesai_20-0113_around_alpha.pkl"
        MAX_NUMBER_OF_VOXELS: 100000
        SHUFFLE_POINTS: true
