_base_: [
    "models/3ddet/tools/cfgs/_base_/models/pointpillars.yaml",
    "models/3ddet/tools/cfgs/_base_/models/rpn_stage_rpn32_48_88_splitHead2.yaml",

    "models/3ddet/tools/cfgs/_base_/dataset/db_sampler.yaml",
    'models/3ddet/tools/cfgs/_base_/dataset/data_augment_use_intensity.yaml',
    # "models/3ddet/tools/cfgs/_base_/dataset/input_data_voxels65536_internal_18W-PK1-2_around.yaml",
    "configs/3ddet/input_data_voxels65536_internal_18W-PK1-2_around_for_1984.yaml",

    "models/3ddet/tools/cfgs/_base_/processor/voxel_generator_max_points16_70x70_4cls.yaml",
    "models/3ddet/tools/cfgs/_base_/processor/quantization_16bit.yaml",
    
    "models/3ddet/tools/cfgs/_base_/schedules/train_lr1e-2_wd5e-4_4cls.yaml",
    "models/3ddet/tools/cfgs/_base_/schedules/test_independent_nms_70x70_4cls_normal_nms.yaml"]


