task:
    # Required (change partition, num_gpus or others where necessary)
    template: "sh runner/{framework}/train.sh pat_dev {gpus} {model} {py_args}"
    # Required
    search_args:
        - type: Nested
          value: [
                    # (un)commit your config here
                    # pod
                    # {'framework': 'pod', 'gpus': 8, 'model': 'faster-rcnn-R50-FPN-1x.benchmark', 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'pod', 'gpus': 8, 'model': 'faster-rcnn-R50-FPN-1x_mix.benchmark', 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'pod', 'gpus': 8, 'model': 'retinanet-R50-1x.benchmark', 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'pod', 'gpus': 8, 'model': 'mask-rcnn-R50-FPN-1x.benchmark', 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'pod', 'gpus': 8, 'model': 'mask-rcnn-R50-FPN-1x_mix.benchmark', 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'pod', 'gpus': 8, 'model': 'keypoint-rcnn-R50-FPN-1x.benchmark', 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'pod', 'gpus': 8, 'model': 'keypoint-rcnn-R50-FPN-1x_mix.benchmark', 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'pod', 'gpus': 8, 'model': 'rfcn-R101-ohem-deform-1x.benchmark', 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'pod', 'gpus': 8, 'model': 'cascade-rcnn-R50-FPN-1x.benchmark', 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'pod', 'gpus': 8, 'model': 'faster-rcnn-mobilenet-FPN-1x.benchmark', 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'pod', 'gpus': 8, 'model': 'faster-rcnn-mobilenet-FPN-1x_mix.benchmark', 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'pod', 'gpus': 8, 'model': 'faster-rcnn-shufflenet-FPN-1x.benchmark', 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'pod', 'gpus': 8, 'model': 'rfcn-mobilenet-1x.benchmark', 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'pod', 'gpus': 8, 'model': 'rfcn-shufflenet-1x.benchmark', 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'pod', 'gpus': 8, 'model': 'grid-rcnn-R50-FPN-2x.benchmark', 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'pod', 'gpus': 8, 'model': 'retinanet-R50-ghm-1x.benchmark', 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'pod', 'gpus': 8, 'model': 'faster-rcnn-R50-FPN-1x-DCN@C3-C5.benchmark', 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'pod', 'gpus': 8, 'model': 'retinanet-R50-GN-FA.benchmark', 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'pod', 'gpus': 8, 'model': 'faster-rcnn-R50-NASFPN-1x_mix.benchmark', 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'pod', 'gpus': 8, 'model': 'faster-rcnn-R50-PAFPN-1x_mix.benchmark', 'py_args': '--pavi --pavi-project parrots_test'},
                    # alphatrion
                    # {'framework': 'alphatrion', 'gpus': 8, 'model': 'mobilenet_v2_fp32_benchmark', 'py_args': '--pavi.use true --pavi.writer.project parrots_test'},
                    # {'framework': 'alphatrion', 'gpus': 8, 'model': 'mobilenet_v2_fp16_benchmark', 'py_args': '--pavi.use true --pavi.writer.project parrots_test'},
                    # {'framework': 'alphatrion', 'gpus': 8, 'model': 'se_resnet50_fp32_benchmark', 'py_args': '--pavi.use true --pavi.writer.project parrots_test'},
                    # {'framework': 'alphatrion', 'gpus': 8, 'model': 'se_resnet50_fp16_benchmark', 'py_args': '--pavi.use true --pavi.writer.project parrots_test'},
                    # {'framework': 'alphatrion', 'gpus': 8, 'model': 'resnet50_fp32_benchmark', 'py_args': '--pavi.use true --pavi.writer.project parrots_test'},
                    # {'framework': 'alphatrion', 'gpus': 8, 'model': 'resnet50_fp16_benchmark', 'py_args': '--pavi.use true --pavi.writer.project parrots_test'},
                    # {'framework': 'alphatrion', 'gpus': 8, 'model': 'resnet101_fp32_benchmark', 'py_args': '--pavi.use true --pavi.writer.project parrots_test'},
                    # {'framework': 'alphatrion', 'gpus': 8, 'model': 'resnet101_fp16_benchmark', 'py_args': '--pavi.use true --pavi.writer.project parrots_test'},
                    # ssd
                    # {'framework': 'ssd', 'gpus': 8, 'model': 'ssd_FSAF_benchmark', 'py_args': '--PAVI.USE true --PAVI.WRITER.PROJECT parrots_test'},
                    # {'framework': 'ssd', 'gpus': 8, 'model': 'ssd_Retina_benchmark', 'py_args': '--PAVI.USE true --PAVI.WRITER.PROJECT parrots_test'},
                    # alphatrion_nas
                    # {'framework': 'alphatrion_nas', 'gpus': 8, 'model': 'super_resnet_range1_benchmark', 'py_args': '--pavi.use true --pavi.writer.project parrots_test'},
                    # {'framework': 'alphatrion_nas', 'gpus': 8, 'model': 'super_resnet_range1_fp16_benchmark', 'py_args': '--pavi.use true --pavi.writer.project parrots_test'},             
                    # seg_nas
                    # {'framework': 'seg_nas', 'gpus': 8, 'model': 'single_path_oneshot_benchmark', 'py_args': '--pavi --pavi_project parrots_test --data_reader MemcachedReader'},
                    # nas_lite
                    # {'framework': 'nas_lite', 'gpus': 32, 'model': 'proxyless_search_benchmark', 'py_args': '--pavi --pavi-project parrots_test'},
                    # example
                    # {'framework': 'example', 'gpus': 8, 'model': "dpn92_mix.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'example', 'gpus': 8, 'model': "dpn92.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'example', 'gpus': 8, 'model': "inception_resnet_mix.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'example', 'gpus': 8, 'model': "inception_resnet.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'example', 'gpus': 8, 'model': "inception_v2_mix.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'example', 'gpus': 8, 'model': "inception_v2.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'example', 'gpus': 8, 'model': "inception_v3_mix.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'example', 'gpus': 8, 'model': "inception_v3.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'example', 'gpus': 8, 'model': "inception_v4_mix.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'example', 'gpus': 8, 'model': "inception_v4.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'example', 'gpus': 8, 'model': "mobile_v2_mix.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'example', 'gpus': 8, 'model': "mobile_v2.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'example', 'gpus': 8, 'model': "resnet101_mix.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'example', 'gpus': 8, 'model': "resnet101.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'example', 'gpus': 8, 'model': "resnet152_mix.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'example', 'gpus': 8, 'model': "resnet152.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'example', 'gpus': 8, 'model': "resnet18_mix.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'example', 'gpus': 8, 'model': "resnet18.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'example', 'gpus': 8, 'model': "resnet50_mix.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'example', 'gpus': 8, 'model': "resnet50.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'example', 'gpus': 8, 'model': "se_resnet50_mix.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'example', 'gpus': 8, 'model': "se_resnet50.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'example', 'gpus': 8, 'model': "shuffle_v2_mix.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # {'framework': 'example', 'gpus': 8, 'model': "shuffle_v2.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # mmaction
                    {'framework': 'mmaction', 'gpus': 8, 'model': 'i3d_r50_video_32x2x1_100e_kinetics400_rgb.benchmark', 'py_args': '--validate --pavi --pavi_project parrots_test'},
                    {'framework': 'mmaction', 'gpus': 8, 'model': 'tsn_r50_video_1x1x8_100e_kinetics400_rgb.benchmark', 'py_args': '--validate --pavi --pavi_project parrots_test'},
                    {'framework': 'mmaction', 'gpus': 8, 'model': 'tsn_r50_video_dense_1x1x8_100e_kinetics400_rgb.benchmark', 'py_args': '--validate --pavi --pavi_project parrots_test'},
                ]
    # Optional
    # callback: "cat"
    callback: "python autotest/parrots_test_callback.py {framework} {model}"

searcher:
    # Support GridSearcher, RandomSearcher, SkoptSearcher
    type: GridSearcher
    # Required
    reward_attribute: acc

scheduler:
    type: FIFO
    parallel_size: 8
    stop_criterion:
        max_tries: 100

# Optional
pavi:
    compare:
        name: parrots.test.benchmark

# slurm_job_id_monitor: true

