task:
    # Required (change partition, num_gpus or others where necessary)
    template: "sh runner/{framework}/train.sh pat_dev {gpus} {model} {py_args}"
    # Required
    search_args:
        - type: Nested
          value: [
                    # (un)commit your config here
                    # pod
                    {'framework': 'pod', 'gpus': 8, 'model': 'mask-rcnn-R50-FPN-1x', 'py_args': '--pavi'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'rfcn-R101-ohem-deform-1x', 'py_args': '--pavi'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'keypoint-rcnn-R50-FPN-1x', 'py_args': '--pavi'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'cascade-rcnn-R50-FPN-1x', 'py_args': '--pavi'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'grid-rcnn-R50-FPN-2x', 'py_args': '--pavi'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'faster-rcnn-R50-NASFPN-1x_mix', 'py_args': '--pavi'},
                    # ssd
                    {'framework': 'ssd', 'gpus': 8, 'model': 'ssd_FSAF', 'py_args': '--PAVI.USE true --PAVI.WRITER.PROJECT parrots_test'},
                    {'framework': 'ssd', 'gpus': 8, 'model': 'ssd_Retina', 'py_args': '--PAVI.USE true --PAVI.WRITER.PROJECT parrots_test'},
                    # alphatrion
                    {'framework': 'alphatrion', 'gpus': 8, 'model': 'resnet50_fp32', 'py_args': '--pavi.use true --pavi.writer.project parrots_test'},
                    # example
                    {'framework': 'example', 'gpus': 8, 'model': "mobile_v2", 'py_args': '--pavi'},
                    {'framework': 'example', 'gpus': 8, 'model': "resnet50_mix", 'py_args': '--pavi'},
                    {'framework': 'example', 'gpus': 8, 'model': "resnet50", 'py_args': '--pavi'},
                    {'framework': 'example', 'gpus': 8, 'model': "inception_v4", 'py_args': '--pavi'},
                    {'framework': 'example', 'gpus': 8, 'model': "se_resnet50_mix", 'py_args': '--pavi'},
                    {'framework': 'example', 'gpus': 8, 'model': "shuffle_v2", 'py_args': '--pavi'},
                ]
    # Optional
    # callback: "cat"
    callback: "python autotest/parrots_test_callback.py {framework} {model}"

searcher:
    # Support GridSearcher, RandomSearcher, SkoptSearcher
    type: GridSearcher
    # Required
    reward_attribute: acc

scheduler:
    type: FIFO
    parallel_size: 8
    stop_criterion:
        max_tries: 100

# Optional
pavi:
    compare:
        name: parrots.test.benchmark

# slurm_job_id_monitor: true

