task:
    # Required (change partition, num_gpus or others where necessary)
    template: "sh runner/{framework}/train.sh pat_dev {gpus} {model} {py_args}"
    # Required
    search_args:
        - type: Nested
          value: [
                    # (un)commit your config here
                    # seg
                    {'framework': 'seg', 'gpus': 16, 'model': 'deeplab.benchmark', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    {'framework': 'seg', 'gpus': 16, 'model': 'pspnet.benchmark', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    # # pod
                    {'framework': 'pod', 'gpus': 8, 'model': 'faster-rcnn-R50-FPN-1x.benchmark', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'retinanet-R50-1x.benchmark', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'mask-rcnn-R50-FPN-1x.benchmark', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'keypoint-rcnn-R50-FPN-1x.benchmark', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'rfcn-R101-ohem-deform-1x.benchmark', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'cascade-rcnn-R50-FPN-1x.benchmark', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'faster-rcnn-mobilenet-FPN-1x.benchmark', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'rfcn-shufflenet-1x.benchmark', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'grid-rcnn-R50-FPN-2x.benchmark', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    # # alphatrion
                    {'framework': 'alphatrion', 'gpus': 8, 'model': 'mobilenet_v2_fp32_benchmark', 'py_args': '--pavi.use true --pavi.writer.project parrots_test --data_reader MemcachedReader --seed 1024'},
                    {'framework': 'alphatrion', 'gpus': 8, 'model': 'mobilenet_v2_fp16_benchmark', 'py_args': '--pavi.use true --pavi.writer.project parrots_test --data_reader MemcachedReader --seed 1024'},
                    {'framework': 'alphatrion', 'gpus': 8, 'model': 'se_resnet50_fp32_benchmark', 'py_args': '--pavi.use true --pavi.writer.project parrots_test --data_reader MemcachedReader --seed 1024'},
                    {'framework': 'alphatrion', 'gpus': 8, 'model': 'se_resnet50_fp16_benchmark', 'py_args': '--pavi.use true --pavi.writer.project parrots_test --data_reader MemcachedReader --seed 1024'},
                    {'framework': 'alphatrion', 'gpus': 8, 'model': 'resnet50_fp32_benchmark', 'py_args': '--pavi.use true --pavi.writer.project parrots_test --data_reader MemcachedReader --seed 1024'},
                    {'framework': 'alphatrion', 'gpus': 8, 'model': 'resnet50_fp16_benchmark', 'py_args': '--pavi.use true --pavi.writer.project parrots_test --data_reader MemcachedReader --seed 1024'},
                    {'framework': 'alphatrion', 'gpus': 8, 'model': 'resnet101_fp32_benchmark', 'py_args': '--pavi.use true --pavi.writer.project parrots_test --data_reader MemcachedReader --seed 1024'},
                    {'framework': 'alphatrion', 'gpus': 8, 'model': 'resnet101_fp16_benchmark', 'py_args': '--pavi.use true --pavi.writer.project parrots_test --data_reader MemcachedReader --seed 1024'},
                    # # ssd
                    {'framework': 'ssd', 'gpus': 8, 'model': 'ssd_FSAF_benchmark', 'py_args': '--PAVI.USE true --PAVI.WRITER.PROJECT parrots_test --DATA_READER MemcachedReader --SEED 1024'},
                    {'framework': 'ssd', 'gpus': 8, 'model': 'ssd_Retina_benchmark', 'py_args': '--PAVI.USE true --PAVI.WRITER.PROJECT parrots_test --DATA_READER MemcachedReader --SEED 1024'},
                    # # example
                    {'framework': 'example', 'gpus': 8, 'model': "dpn92.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    {'framework': 'example', 'gpus': 8, 'model': "inception_v3.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    {'framework': 'example', 'gpus': 8, 'model': "inception_v4.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    {'framework': 'example', 'gpus': 8, 'model': "resnet50.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    {'framework': 'example', 'gpus': 8, 'model': "se_resnet50.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    {'framework': 'example', 'gpus': 8, 'model': "shuffle_v2.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    {'framework': 'example', 'gpus': 8, 'model': "vgg16.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    {'framework': 'example', 'gpus': 8, 'model': "shuffle_v1.benchmark", 'py_args': '--pavi --pavi-project parrots_test'},
                    # star
                    # {'framework': 'star', 'gpus': 8, 'model': "topdown_resnet50.benchmark", 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    # {'framework': 'star', 'gpus': 8, 'model': "topdown_resnest50.benchmark", 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    # {'framework': 'star', 'gpus': 8, 'model': "topdown_jnet.benchmark", 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    # {'framework': 'star', 'gpus': 8, 'model': "topdown_hrnet32.benchmark", 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    # {'framework': 'star', 'gpus': 8, 'model': "bottomup_jnet.benchmark", 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    # {'framework': 'star', 'gpus': 8, 'model': "bottomup_hrnet32.benchmark", 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                ]
    # Optional
    # callback: "cat"
    pre_callback: "python autotest/parrots_test_callback_new.py {framework} {model} 0 weeklybenchmark"
    after_callback: "python autotest/parrots_test_callback_new.py {framework} {model} 1 weeklybenchmark"

searcher:
    # Support GridSearcher, RandomSearcher, SkoptSearcher
    type: GridSearcher
    # Required
    reward_attribute: acc

scheduler:
    type: FIFO
    parallel_size: 8
    stop_criterion:
        max_tries: 100
    wait_to_run_time_thresh: 12 # inf

# Optional
pavi:
    compare:
        name: parrots.test.weeklybenchmark

# slurm_job_id_monitor: true
