task:
    # Required (change partition, num_gpus or others where necessary)
    template: "sh runner/{framework}/train.sh pat_dailybuild {gpus} {model} {py_args}"
    # Required
    search_args:
        - type: Nested
          value: [
                    # (un)commit your config here
                    {'framework': 'example', 'gpus': 16, 'model': "resnet18_mix.short", 'py_args': '--data_reader CephReader'}, #example
                    # pod
                    {'framework': 'pod', 'gpus': 8, 'model': 'rfcn-mobilenet-1x', 'py_args': '--data_reader CephReader'},
                    # mmpose
                    {'framework': 'mmpose', 'gpus': 8, 'model': 'topdown_alexnet', 'py_args': '--data_reader CephReader --seed 1024 --max-step 10'},
                    # mmediting
                    {'framework': 'mmediting', 'gpus': 1, 'model': 'cyclegan_lsgan_id0_resnet_in_1x1_246200_summer2winter', 'py_args': '--data-reader CephReader --seed 1024  --max-step 24650'},
                    # mmaction
                    {'framework': 'mmaction', 'gpus': 8, 'model': 'bmn_400x100_2x8_9e_activitynet_feature', 'py_args': '--data_reader MemcachedReader --seed 1024 --max-step 6'},
                    # mmdet
                    {'framework': 'mmdet', 'gpus': 8, 'model': 'mask_rcnn_r50_fpn_1x_coco', 'py_args': '--data_reader CephReader --seed 1024 --max-step 1'},
                    # pod
                    {'framework': 'pod', 'gpus': 8, 'model': 'faster-rcnn-R50-C4-1x.short', 'py_args': '--seed 1024 --data_reader CephReader'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'keypoint-rcnn-R50-FPN-1x.short', 'py_args': '--seed 1024 --data_reader CephReader'},
                    # example
                    {'framework': 'example', 'gpus': 8, 'model': "mobile_v1.short", 'py_args': '--data_reader MemcachedReader'},
                    {'framework': 'example', 'gpus': 8, 'model': "inceptionv3.short", 'py_args': '--data_reader MemcachedReader'},
                    {'framework': 'example', 'gpus': 8, 'model': "resnet50.short", 'py_args': '--data_reader MemcachedReader'},
                    {'framework': 'example', 'gpus': 8, 'model': "resnet50_sync.short", 'py_args': '--data_reader MemcachedReader'},
                ]
    # Optional
    # callback: "cat"
    pre_callback: "python autotest/parrots_test_callback_new.py {framework} {model} 0 dailytest"
    after_callback: "python autotest/parrots_test_callback_new.py {framework} {model} 1 dailytest"

searcher:
    # Support GridSearcher, RandomSearcher, SkoptSearcher
    type: GridSearcher
    # Required
    reward_attribute: acc

scheduler:
    type: FIFO
    parallel_size: 20
    stop_criterion:
        max_tries: 100
    wait_to_run_time_thresh: inf # inf
    wait_to_get_pavi_task_thresh: 0.5

# Optional
#pavi:
#    compare:
#        name: parrots.test.dailytest

# slurm_job_id_monitor: true

