task:
    # Required (change partition, num_gpus or others where necessary)
    template: "sh runner/{framework}/train.sh pat_weeklybuild {gpus} {model} {py_args}"
    # Required
    search_args:
        - type: Nested
          value: [
                    # (un)commit your config here
                    ## 3.alphatrion
                    {'framework': 'alphatrion', 'gpus': 8, 'model': 'mobilenet_v2_fp32', 'py_args': '--pavi.use true --pavi.writer.project parrots_test --data_reader MemcachedReader --seed 1024'},
                    {'framework': 'alphatrion', 'gpus': 8, 'model': 'mobilenet_v2_fp16', 'py_args': '--pavi.use true --pavi.writer.project parrots_test --data_reader MemcachedReader --seed 1024'},
                    {'framework': 'alphatrion', 'gpus': 8, 'model': 'se_resnet50_fp32', 'py_args': '--pavi.use true --pavi.writer.project parrots_test --data_reader MemcachedReader --seed 1024'},
                    {'framework': 'alphatrion', 'gpus': 8, 'model': 'se_resnet50_fp16', 'py_args': '--pavi.use true --pavi.writer.project parrots_test --data_reader MemcachedReader --seed 1024'},
                    {'framework': 'alphatrion', 'gpus': 8, 'model': 'resnet50_fp16', 'py_args': '--pavi.use true --pavi.writer.project parrots_test --data_reader MemcachedReader --seed 1024'},
                    {'framework': 'alphatrion', 'gpus': 8, 'model': 'resnet101_fp32', 'py_args': '--pavi.use true --pavi.writer.project parrots_test --data_reader MemcachedReader --seed 1024'},
                    {'framework': 'alphatrion', 'gpus': 8, 'model': 'resnet101_fp16', 'py_args': '--pavi.use true --pavi.writer.project parrots_test --data_reader MemcachedReader --seed 1024'},
                    ## 6.alphatrion_nas
                    {'framework': 'alphatrion_nas', 'gpus': 8, 'model': 'super_resnet_range1', 'py_args': '--pavi.use true --pavi.writer.project parrots_test --data_reader MemcachedReader --seed 1024'},
                    {'framework': 'alphatrion_nas', 'gpus': 8, 'model': 'super_resnet_range1_fp16', 'py_args': '--pavi.use true --pavi.writer.project parrots_test --data_reader MemcachedReader --seed 1024'},
                    ## 8.example
                    {'framework': 'example', 'gpus': 8, 'model': "dpn92_mix", 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader'},
                    {'framework': 'example', 'gpus': 8, 'model': "dpn92", 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader'},
                    {'framework': 'example', 'gpus': 8, 'model': "inception_resnet_mix", 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader'},
                    {'framework': 'example', 'gpus': 8, 'model': "inception_resnet", 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader'},
                    {'framework': 'example', 'gpus': 8, 'model': "inception_v2_mix", 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader'},
                    {'framework': 'example', 'gpus': 8, 'model': "inception_v2", 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader'},
                    {'framework': 'example', 'gpus': 8, 'model': "inception_v3_mix", 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader'},
                    {'framework': 'example', 'gpus': 8, 'model': "inception_v3", 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader'},
                    {'framework': 'example', 'gpus': 8, 'model': "inception_v4_mix", 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader'},
                    {'framework': 'example', 'gpus': 8, 'model': "mobile_v2_mix", 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader'},
                    {'framework': 'example', 'gpus': 8, 'model': "resnet101_mix", 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader'},
                    {'framework': 'example', 'gpus': 8, 'model': "resnet101", 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader'},
                    {'framework': 'example', 'gpus': 8, 'model': "resnet152_mix", 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader'},
                    {'framework': 'example', 'gpus': 8, 'model': "resnet152", 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader'},
                    {'framework': 'example', 'gpus': 8, 'model': "resnet18_mix", 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader'},
                    {'framework': 'example', 'gpus': 8, 'model': "resnet18", 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader'},
                    {'framework': 'example', 'gpus': 8, 'model': "se_resnet50", 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader'},
                    {'framework': 'example', 'gpus': 8, 'model': "shuffle_v2_mix", 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader'},
                    ## 1.mmdet
                    {'framework': 'mmdet', 'gpus': 8, 'model': 'mask_rcnn_x101_32x4d_fpn_1x_coco', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    {'framework': 'mmdet', 'gpus': 8, 'model': 'faster_rcnn_r50_fpn_1x_coco', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    {'framework': 'mmdet', 'gpus': 8, 'model': 'retinanet_r50_fpn_fp16_1x_coco', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    {'framework': 'mmdet', 'gpus': 8, 'model': 'mask_rcnn_r101_fpn_1x_coco', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    {'framework': 'mmdet', 'gpus': 8, 'model': 'cascade_mask_rcnn_r50_fpn_1x_coco', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    {'framework': 'mmdet', 'gpus': 8, 'model': 'mask_rcnn_r50_caffe_fpn_mstrain_1x_coco', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    {'framework': 'mmdet', 'gpus': 8, 'model': 'mask_rcnn_x101_64x4d_fpn_1x_coco', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    {'framework': 'mmdet', 'gpus': 8, 'model': 'faster_rcnn_r50_fpn_dconv_c3-c5_1x_coco', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    #{'framework': 'mmdet', 'gpus': 8, 'model': 'fsaf_r50_fpn_1x_coco', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'}, 
                    ## 2.pod
                    {'framework': 'pod', 'gpus': 8, 'model': 'faster-rcnn-R50-FPN-1x', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'faster-rcnn-R50-FPN-1x_mix', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'retinanet-R50-1x', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'mask-rcnn-R50-FPN-1x_mix', 'py_args': '--pavi --pavi-project parrots_test --seed 1024'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'keypoint-rcnn-R50-FPN-1x_mix', 'py_args': '--pavi --pavi-project parrots_test'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'faster-rcnn-mobilenet-FPN-1x', 'py_args': '--pavi --pavi-project parrots_test'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'faster-rcnn-mobilenet-FPN-1x_mix', 'py_args': '--pavi --pavi-project parrots_test'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'faster-rcnn-shufflenet-FPN-1x', 'py_args': '--pavi --pavi-project parrots_test'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'rfcn-mobilenet-1x', 'py_args': '--pavi --pavi-project parrots_test'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'rfcn-shufflenet-1x', 'py_args': '--pavi --pavi-project parrots_test'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'retinanet-R50-ghm-1x', 'py_args': '--pavi --pavi-project parrots_test'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'faster-rcnn-R50-FPN-1x-DCN@C3-C5', 'py_args': '--pavi --pavi-project parrots_test'},
                    {'framework': 'pod', 'gpus': 8, 'model': 'retinanet-R50-GN-FA', 'py_args': '--pavi --pavi-project parrots_test'},
                    {'framework': 'pod', 'gpus': 16, 'model': 'faster-rcnn-R50-PAFPN-1x_mix', 'py_args': '--pavi --pavi-project parrots_test'},
                    ##4.seg_nas
                    {'framework': 'seg_nas', 'gpus': 8, 'model': 'single_path_oneshot', 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader --seed 1024'},
                    ## 7.seg
                    {'framework': 'seg', 'gpus': 16, 'model': 'pspnet', 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader'},
                    ## 12.mmaction
                    {'framework': 'mmaction', 'gpus': 8, 'model': 'i3d_r50_video_32x2x1_100e_kinetics400_rgb', 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader --seed 1024'},
                    {'framework': 'mmaction', 'gpus': 8, 'model': 'tsn_r50_video_1x1x8_100e_kinetics400_rgb', 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader --seed 1024'},
                    {'framework': 'mmaction', 'gpus': 2, 'model': 'bmn_400x100_2x8_9e_activitynet_feature', 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader --seed 1024'},
                    ## 14.mmediting
                    {'framework': 'mmediting', 'gpus': 1, 'model': 'cyclegan_lsgan_id0_resnet_in_1x1_246200_summer2winter', 'py_args': '--pavi --pavi-project parrots_test --data-reader MemcachedReader --seed 1024'},
                    {'framework': 'mmediting', 'gpus': 1, 'model': 'edsr_x2c64b16_g1_300k_div2k', 'py_args': '--pavi --pavi-project parrots_test --data-reader MemcachedReader --seed 1024'},
                    {'framework': 'mmediting', 'gpus': 1, 'model': 'dim_stage2_v16_pln_1x1_1000k_comp1k', 'py_args': '--pavi --pavi-project parrots_test --data-reader MemcachedReader --seed 1024'},
                    {'framework': 'mmediting', 'gpus': 8, 'model': 'gl_256x256_8x12_celeba', 'py_args': '--pavi --pavi-project parrots_test --data-reader MemcachedReader --seed 1024'},
                ]
    # Optional
    # callback: "cat"
    pre_callback: "python autotest/parrots_test_callback_new.py {framework} {model} 0 weeklytest"
    after_callback: "python autotest/parrots_test_callback_new.py {framework} {model} 1 weeklytest"

searcher:
    # Support GridSearcher, RandomSearcher, SkoptSearcher
    type: GridSearcher
    # Required
    reward_attribute: acc

scheduler:
    type: FIFO
    parallel_size: 60
    stop_criterion:
        max_tries: 100
    wait_to_run_time_thresh: inf # inf

# Optional
pavi:
    compare:
        name: parrots.test.weeklytest

# slurm_job_id_monitor: true

