task:
    # Required (change partition, num_gpus or others where necessary)
    template: "sh runner/spc_run.sh wenli {framework} {model} {gpus} {py_args}"
    # Required
    search_args:
        - type: Nested
          value: [
                # (un)commit your config here
                ## 0.demo
              #  {'framework': 'deformable_detr', 'gpus': 8, 'model': 'r50_deformable_detr_plus_iterative_bbox_refinement_plus_plus_two_stage', 'py_args': '--pavi --pavi-project default --data_reader CephReader --seed 1024 --num_workers 0 --max_step 1'},
              ## 1.mmediting
              #{'framework': 'mmediting', 'gpus': 1, 'model': 'cyclegan_lsgan_id0_resnet_in_1x1_246200_summer2winter', 'py_args': '--pavi --pavi-project parrots_test --data-reader MemcachedReader --seed 1024 --max-step 500'},
              # {'framework': 'mmediting', 'gpus': 8, 'model': 'deepfillv2_256x256_8x2_celeba', 'py_args': '--pavi --pavi-project parrots_test --data-reader MemcachedReader --seed 1024 --max-step 500'},
              # {'framework': 'mmediting', 'gpus': 1, 'model': 'dim_stage2_v16_pln_1x1_1000k_comp1k', 'py_args': '--pavi --pavi-project parrots_test --data-reader MemcachedReader --seed 1024 --max-step 500'},
              # {'framework': 'mmediting', 'gpus': 1, 'model': 'edsr_x2c64b16_g1_300k_div2k', 'py_args': '--pavi --pavi-project parrots_test --data-reader MemcachedReader --seed 1024 --max-step 500'},
              # {'framework': 'mmediting', 'gpus': 1, 'model': 'esrgan_psnr_x4c64b23g32_g1_1000k_div2k', 'py_args': '--pavi --pavi-project parrots_test --data-reader MemcachedReader --seed 1024 --max-step 500'},
              # {'framework': 'mmediting', 'gpus': 8, 'model': 'gl_256x256_8x12_celeba', 'py_args': '--pavi --pavi-project parrots_test --data-reader MemcachedReader --seed 1024 --max-step 500'},
              # {'framework': 'mmediting', 'gpus': 1, 'model': 'indexnet_mobv2_1x16_78k_comp1k', 'py_args': '--pavi --pavi-project parrots_test --data-reader MemcachedReader --seed 1024 --max-step 500'},
              # {'framework': 'mmediting', 'gpus': 1, 'model': 'msrresnet_x4c64b16_g1_1000k_div2k', 'py_args': '--pavi --pavi-project parrots_test --data-reader MemcachedReader --seed 1024 --max-step 500'},
              # {'framework': 'mmediting', 'gpus': 8, 'model': 'pconv_256x256_stage1_8x1_celeba', 'py_args': '--pavi --pavi-project parrots_test --data-reader MemcachedReader --seed 1024 --max-step 500'},
              # {'framework': 'mmediting', 'gpus': 1, 'model': 'pix2pix_vanilla_unet_bn_1x1_80k_facades', 'py_args': '--pavi --pavi-project parrots_test --data-reader MemcachedReader --seed 1024 --max-step 500'},
              # {'framework': 'mmediting', 'gpus': 1, 'model': 'srcnn_x4k915_g1_1000k_div2k', 'py_args': '--pavi --pavi-project parrots_test --data-reader MemcachedReader --seed 1024 --max-step 500'},
            
            ]
    # Optional
    # callback: "cat"
    pre_callback: "python autotest/parrots_test_callback_new.py {framework} {model} 0 all"
    after_callback: "python autotest/parrots_test_callback_new.py {framework} {model} 1 all"

searcher:
    # Support GridSearcher, RandomSearcher, SkoptSearcher
    type: GridSearcher
    # Required
    reward_attribute: acc

scheduler:
    type: FIFO
    parallel_size: 8
    stop_criterion:
        max_tries: 100
    wait_to_run_time_thresh: inf # inf

# Optional
pavi:
    compare:
        name: parrots.test

# slurm_job_id_monitor: true

# is run job on Container?
container: True
