task:
    # Required (change partition, num_gpus or others where necessary)
    template: "PARROTS_BENCHMARK=1 sh runner/spc_run.sh #your-namespace# {framework} {model} {gpus} {py_args}"
    # Required
    search_args:
        - type: Nested
          value: [
                    # (un)commit your config here, same as search_config_benchmark.yaml
                    ## 5.ssd
                    # {'framework': 'ssd', 'gpus': 8, 'model': 'ssd_FSAF_benchmark', 'py_args': '--PAVI.USE true --PAVI.WRITER.PROJECT default --DATA_READER CephReader --SEED 1024'},
                    # {'framework': 'ssd', 'gpus': 8, 'model': 'ssd_Retina_benchmark', 'py_args': '--PAVI.USE true --PAVI.WRITER.PROJECT default --DATA_READER CephReader --SEED 1024'},
                    
                ]
    # Optional
    # callback: "cat"
    pre_callback: "python autotest/parrots_test_callback_new.py {framework} {model} 0 all"
    after_callback: "python autotest/parrots_test_callback_new.py {framework} {model} 1 all"

searcher:
    # Support GridSearcher, RandomSearcher, SkoptSearcher
    type: GridSearcher
    # Required
    reward_attribute: acc

scheduler:
    type: FIFO
    parallel_size: 8
    stop_criterion:
        max_tries: 100
    wait_to_run_time_thresh: inf # inf

# Optional
pavi:
    compare:
        name: parrots.test

# slurm_job_id_monitor: true

# is run job on Container?
container: True
