task:
    # Required (change partition, num_gpus or others where necessary)
    template: "sh runner/{framework}/train.sh pat_dev {gpus} {model} {py_args}"
    # Required
    search_args:
        - type: Nested
          value: [
                    # (un)commit your config here
                    {'framework': 'example', 'gpus': 16, 'model': "resnet18_mix.short", 'py_args': '--pavi --pavi-project pulin --data_reader MemcachedReader --seed 1024'}, 
                    {'framework': 'example', 'gpus': 16, 'model': "resnet18_mix.short", 'py_args': '--pavi --pavi-project pulin --data_reader MemcachedReader --seed 888'}, 
                    {'framework': 'example', 'gpus': 16, 'model': "resnet18_mix.short", 'py_args': '--pavi --pavi-project pulin --data_reader MemcachedReader --seed 666'}, 
                    {'framework': 'example', 'gpus': 16, 'model': "resnet18_mix.short", 'py_args': '--pavi --pavi-project pulin --data_reader MemcachedReader --seed 555'}, 
                    {'framework': 'example', 'gpus': 16, 'model': "resnet18_mix.short", 'py_args': '--pavi --pavi-project pulin --data_reader MemcachedReader --seed 111'}, 
                    {'framework': 'example', 'gpus': 8, 'model': "resnet18.short", 'py_args': '--pavi --pavi-project pulin --data_reader MemcachedReader --seed 1024'},
                    {'framework': 'example', 'gpus': 8, 'model': "resnet18.short", 'py_args': '--pavi --pavi-project pulin --data_reader MemcachedReader --seed 888'},
                    {'framework': 'example', 'gpus': 8, 'model': "resnet18.short", 'py_args': '--pavi --pavi-project pulin --data_reader MemcachedReader --seed 166'},
                    {'framework': 'example', 'gpus': 8, 'model': "resnet18.short", 'py_args': '--pavi --pavi-project pulin --data_reader MemcachedReader --seed 111'},
                    {'framework': 'example', 'gpus': 8, 'model': "resnet18.short", 'py_args': '--pavi --pavi-project pulin --data_reader MemcachedReader --seed 555'},
                ]
    # Optional
    # callback: "cat"
    pre_callback: "python autotest/parrots_test_callback_new.py {framework} {model} 0 dailytest"
    after_callback: "python autotest/parrots_test_callback_new.py {framework} {model} 1 dailytest"

searcher:
    # Support GridSearcher, RandomSearcher, SkoptSearcher
    type: GridSearcher
    # Required
    reward_attribute: acc

scheduler:
    type: FIFO
    parallel_size: 10
    stop_criterion:
        max_tries: 100
    wait_to_run_time_thresh: inf # inf

# Optional
pavi:
    compare:
        name: pyt1.1_example

# slurm_job_id_monitor: true

