act_type: relu
resolution: SearchAxis(160)@[128, 160, 192]
se_ratio: null
se_size: null
se_type: null
se_use: 0
stages:
-   block_type: GluonInputBlock
    in_channels: 3
    kernel_size: 3
    name: input_stage
    num_blocks: 1
    out_channels: SearchAxis(24)@[16, 24, 32]
-   block_type: ResidualBlock
    grouch: SearchAxis(8)@[4, 6, 8, 12]
    groups: 1
    kernel_size: SearchAxis(3)@[3]
    name: stage1
    num_blocks: SearchAxis(4)@[1, 2, 3, 4, 5, 6]
    out_channels: SearchAxis(64)@[32, 48, 64, 96]
    stride: 1
-   block_type: ResidualBlock
    grouch: SearchAxis(24)@[12, 16, 24, 32]
    groups: 1
    kernel_size: SearchAxis(3)@[3]
    name: stage2
    num_blocks: SearchAxis(5)@[3, 4, 5, 6, 7]
    out_channels: SearchAxis(128)@[64, 96, 128, 192]
    stride: 2
-   block_type: ResidualBlock
    grouch: SearchAxis(48)@[24, 32, 48, 64, 96]
    groups: 1
    kernel_size: SearchAxis(3)@[3]
    name: stage3
    num_blocks: SearchAxis(5)@[4, 5, 6]
    out_channels: SearchAxis(384)@[256, 384, 512]
    stride: 2
-   block_type: ResidualBlock
    grouch: SearchAxis(96)@[48, 64, 96, 128, 192]
    groups: 1
    kernel_size: SearchAxis(3)@[3]
    name: stage4
    num_blocks: SearchAxis(5)@[3, 4, 5, 6]
    out_channels: SearchAxis(1536)@[768, 1024, 1536, 2048]
    stride: 2