seed: 99
net:
    arch: inception_v3  # inception_v1, inception_v2, inception_v3
    kwargs:
        num_classes: 1000
 
dataset:
  train:
    meta_file: /mnt/lustre/share/images/meta/train.txt
    image_dir: /mnt/lustre/share/images/train
    random_resize_crop: 299
    colorjitter: [0.2, 0.2, 0.2, 0.1]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: True
  test:
    meta_file: /mnt/lustre/share/images/meta/val.txt
    image_dir: /mnt/lustre/share/images/val
    resize: 331
    center_crop: [299, 299]
    colorjitter:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: False
  batch_size: 64
  workers: 4
 
trainer:
  max_epoch: 1
  test_freq: 1
  log_freq: 20
  req_acc: 75.96
  optimizer:
    type: SGD
    kwargs:
      card_4:
        lr: 0.045
        momentum: 0.9
        weight_decay: 0.00004
      card_8:
        lr: 0.1
        momentum: 0.9
        weight_decay: 0.0001
  lr_scheduler:
    warmup_epochs: 0
    type: MultiStepLR
    kwargs:
      milestones: [30,60,90]
      gamma: 0.1
 
saver:
  pretrian_model: 
  resume_model: 
  save_dir: checkpoints/inception_v3   # save checkpoint locally
