seed: 99
net:
    type: inception_resnet_v1  # inception_resnet_v2
    kwargs:
        num_classes: 1000
 
dataset:
  train:
    meta_file: /mnt/lustre/share/images/meta/train.txt
    image_dir: /mnt/lustre/share/images/train
    reader: pillow
    random_crop:
    random_resize_crop: 299
    colorjitter: [0.2, 0.2, 0.2, 0.1]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: True
  test:
    meta_file: /mnt/lustre/share/images/meta/val.txt
    image_dir: /mnt/lustre/share/images/val
    reader: pillow
    resize: 341
    center_crop: [299, 299]
    colorjitter:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: False
  batch_size: 32
  workers: 4
 
trainer:
  max_epoch: 120
  test_freq: 2
  log_freq: 100
  label_smooth:
  optimizer:
    type: SGD
    kwargs:
      lr: 0.045
      momentum: 0.9
      weight_decay: 0.00004
  lr_scheduler:
    warmup_epochs: 0
    type: CosineLR
    kwargs:
      min_lr: 0.0
 
saver:
  pretrian_model: 
  resume_model: 
  save_dir: checkpoints   # save checkpoint locally
  save_epoch_freq: 1
  save_latest: False
  save_best: False
 
monitor:
  type: pavi
  kwargs:
    project: default
    task: inception_resnet_v1
    model: inception_resnet_v1