seed: 99
net:
    arch: mobile_v2
    kwargs:
        num_classes: 1000
        scale: 1.0

dataset:
  train:
    meta_file: /mnt/lustre/share/images/meta/train.txt
    ceph_meta_file: s3://parrots_model_data/imagenet/images/meta/train.txt
    image_dir: /mnt/lustre/share/images/train
    ceph_image_dir: s3://parrots_model_data/imagenet/images/train/
    reader: pillow
    random_resize_crop: 224
    colorjitter: [0.2, 0.2, 0.2, 0.1]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: True
  test:
    meta_file: /mnt/lustre/share/images/meta/val.txt
    ceph_meta_file: s3://parrots_model_data/imagenet/images/meta/val.txt
    image_dir: /mnt/lustre/share/images/val
    ceph_image_dir: s3://parrots_model_data/imagenet/images/val/
    reader: pillow
    resize: 256
    center_crop: [224, 224]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: False
  batch_size: 64 # 4 card
  workers: 6

trainer:
  max_epoch: 150
  test_freq: 1
  log_freq: 200
  req_acc1: 70.37
  label_smooth:
  optimizer:
    type: SGD
    kwargs:
      lr: 0.05
      momentum: 0.9
      weight_decay: 0.00004
  lr_scheduler:
    warmup_epochs: 0
    type: MultiStepLR
    kwargs:
      milestones: [30,60,90]
      gamma: 0.1

saver:
  pretrian_model:
  resume_model:
  save_dir: checkpoints/mobile_v2   # save checkpoint locally
  save_epoch_freq: 240
  save_latest: False
  save_best: True
  sync_bn_stats: False
