seed: 99
net:
    type: se_resnet50  # se_resnet101, se_resnet152, senet154
                       # se_resnext50_32x4d, se_resnext101_32x4d, se_resnext101_64x4d
    kwargs:
        num_classes: 1000
    #bn:
    #    group_size: 1
    #fp16:
    #    scale_factor: 1024
 
dataset:
  train:
    meta_file: /mnt/lustre/share/images/meta/train.txt
    image_dir: /mnt/lustre/share/images/train
    random_resize_crop: 224
    colorjitter: [0.2, 0.2, 0.2, 0.1]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: True
  test:
    meta_file: /mnt/lustre/share/images/meta/val.txt
    image_dir: /mnt/lustre/share/images/val
    resize: 256
    center_crop: [224, 224]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: False
  batch_size: 32
  workers: 4
 
trainer:
  max_epoch: 100
  test_freq: 1
  log_freq: 20
  bn:
    syncbn: False
  mixed_precision:
    half: False
    loss_scale: 128.0
    float_layers:  # define floating layers when mixed training
     # loss:
     #     float_out: True
  optimizer:
    type: SGD
    kwargs:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0001
  lr_scheduler:
    warmup_epochs: 0
    type: MultiStepLR
    kwargs:
      milestones: [30,60,90]
      gamma: 0.1

saver:
  pretrian_model: 
  resume_model: 
  save_dir: checkpoints/se_resnet50   # save checkpoint locally
 
monitor:
  type: pavi
  kwargs:
    project: default
    task: se_resnet50
    model: se_resnet50
