seed: 99
net:
    arch: vgg16 # vgg11, vgg11_bn, vgg13, vgg13_bn, vgg16_bn, vgg19, vgg19_bn
    kwargs:
        num_classes: 1000

dataset:
  train:
    meta_file: /mnt/lustre/share/images/meta/train.txt
    image_dir: /mnt/lustre/share/images/train
    random_resize_crop: 224
    colorjitter: [0.2, 0.2, 0.2, 0.1]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: True
  test:
    meta_file: /mnt/lustre/share/images/meta/val.txt
    image_dir: /mnt/lustre/share/images/val
    resize: 256
    center_crop: [224, 224]
    colorjitter:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: False
  batch_size: 128 # 4 card
  workers: 6

trainer:
  max_epoch: 120
  test_freq: 1
  log_freq: 200
  req_acc: 70.55
  optimizer:
    type: SGD
    kwargs:
      card_4:
        lr: 0.02
        momentum: 0.9
        weight_decay: 0.0001
      card_8:
        lr: 0.02
        momentum: 0.9
        weight_decay: 0.0001
  lr_scheduler:
    warmup_epochs: 0
    type: StepLR
    kwargs:
      step_size: 30
      gamma: 0.1

saver:
  pretrain_model:
  resume_model:
  save_dir: checkpoints/vgg16   # save checkpoint locally
