act_type: relu6
input_stage:
    in_channels: 3
    kernel_size1: SearchAxis(3)@[3, 5]
    kernel_size2: SearchAxis(3)@[3, 5]
    kernel_size3: 1
    neck_channels: SearchAxis(32)@[16, 20, 24, 28, 32, 40, 48, 56, 64]
    out_channels: SearchAxis(16)@[8, 10, 12, 14, 16, 20, 24, 28, 32]
mbconv_stages:
-   blocks:
    -   kernel_size1: 1
        kernel_size2: SearchAxis(3)@[3, 5]
        kernel_size3: 1
        neck_channels: SearchAxis(96)@[48, 56, 64, 80, 96, 112, 128, 160, 192]
        se_size: 0
        use_se: 0
    -   kernel_size1: 1
        kernel_size2: SearchAxis(3)@[3, 5]
        kernel_size3: 1
        neck_channels: SearchAxis(144)@[80, 96, 112, 128, 144, 160, 192, 224, 256]
        se_size: 0
        use_se: 0
    -   kernel_size1: 1
        kernel_size2: SearchAxis(3)@[3, 5]
        kernel_size3: 1
        neck_channels: SearchAxis(144)@[80, 96, 112, 128, 144, 160, 192, 224, 256]
        se_size: 0
        use_se: 0
    num_blocks: SearchAxis(2)@[1, 2, 3]
    out_channels: SearchAxis(24)@[12, 14, 16, 20, 24, 28, 32, 40, 48]
    stride: 2
-   blocks:
    -   kernel_size1: 1
        kernel_size2: SearchAxis(3)@[3, 5]
        kernel_size3: 1
        neck_channels: SearchAxis(144)@[80, 96, 112, 128, 144, 160, 192, 224, 256]
        se_size: 0
        use_se: 0
    -   kernel_size1: 1
        kernel_size2: SearchAxis(3)@[3, 5]
        kernel_size3: 1
        neck_channels: SearchAxis(192)@[96, 112, 128, 160, 192, 224, 256, 320, 384]
        se_size: 0
        use_se: 0
    -   kernel_size1: 1
        kernel_size2: SearchAxis(3)@[3, 5]
        kernel_size3: 1
        neck_channels: SearchAxis(192)@[96, 112, 128, 160, 192, 224, 256, 320, 384]
        se_size: 0
        use_se: 0
    -   kernel_size1: 1
        kernel_size2: SearchAxis(3)@[3, 5]
        kernel_size3: 1
        neck_channels: SearchAxis(192)@[96, 112, 128, 160, 192, 224, 256, 320, 384]
        se_size: 0
        use_se: 0
    num_blocks: SearchAxis(3)@[2, 3, 4]
    out_channels: SearchAxis(32)@[16, 20, 24, 28, 32, 40, 48, 56, 64]
    stride: 2
-   blocks:
    -   kernel_size1: 1
        kernel_size2: SearchAxis(3)@[3, 5]
        kernel_size3: 1
        neck_channels: SearchAxis(192)@[96, 112, 128, 160, 192, 224, 256, 320, 384]
        se_size: 0
        use_se: 0
    -   kernel_size1: 1
        kernel_size2: SearchAxis(3)@[3, 5]
        kernel_size3: 1
        neck_channels: SearchAxis(384)@[192, 224, 256, 320, 384, 448, 512, 640, 768]
        se_size: 0
        use_se: 0
    -   kernel_size1: 1
        kernel_size2: SearchAxis(3)@[3, 5]
        kernel_size3: 1
        neck_channels: SearchAxis(384)@[192, 224, 256, 320, 384, 448, 512, 640, 768]
        se_size: 0
        use_se: 0
    -   kernel_size1: 1
        kernel_size2: SearchAxis(3)@[3, 5]
        kernel_size3: 1
        neck_channels: SearchAxis(384)@[192, 224, 256, 320, 384, 448, 512, 640, 768]
        se_size: 0
        use_se: 0
    -   kernel_size1: 1
        kernel_size2: SearchAxis(3)@[3, 5]
        kernel_size3: 1
        neck_channels: SearchAxis(384)@[192, 224, 256, 320, 384, 448, 512, 640, 768]
        se_size: 0
        use_se: 0
    num_blocks: SearchAxis(4)@[3, 4, 5]
    out_channels: SearchAxis(64)@[32, 40, 48, 56, 64, 80, 96, 112, 128]
    stride: 2
-   blocks:
    -   kernel_size1: 1
        kernel_size2: SearchAxis(3)@[3, 5]
        kernel_size3: 1
        neck_channels: SearchAxis(384)@[192, 224, 256, 320, 384, 448, 512, 640, 768]
        se_size: 0
        use_se: 0
    -   kernel_size1: 1
        kernel_size2: SearchAxis(3)@[3, 5]
        kernel_size3: 1
        neck_channels: SearchAxis(576)@[320, 384, 448, 512, 576, 640, 768, 896, 1024]
        se_size: 0
        use_se: 0
    -   kernel_size1: 1
        kernel_size2: SearchAxis(3)@[3, 5]
        kernel_size3: 1
        neck_channels: SearchAxis(576)@[320, 384, 448, 512, 576, 640, 768, 896, 1024]
        se_size: 0
        use_se: 0
    -   kernel_size1: 1
        kernel_size2: SearchAxis(3)@[3, 5]
        kernel_size3: 1
        neck_channels: SearchAxis(576)@[320, 384, 448, 512, 576, 640, 768, 896, 1024]
        se_size: 0
        use_se: 0
    num_blocks: SearchAxis(3)@[2, 3, 4]
    out_channels: SearchAxis(96)@[48, 56, 64, 80, 96, 112, 128, 160, 192]
    stride: 1
-   blocks:
    -   kernel_size1: 1
        kernel_size2: SearchAxis(3)@[3, 5]
        kernel_size3: 1
        neck_channels: SearchAxis(576)@[320, 384, 448, 512, 576, 640, 768, 896, 1024]
        se_size: 0
        use_se: 0
    -   kernel_size1: 1
        kernel_size2: SearchAxis(3)@[3, 5]
        kernel_size3: 1
        neck_channels: SearchAxis(960)@[512, 640, 768, 896, 960, 1024, 1280, 1536, 1792]
        se_size: 0
        use_se: 0
    -   kernel_size1: 1
        kernel_size2: SearchAxis(3)@[3, 5]
        kernel_size3: 1
        neck_channels: SearchAxis(960)@[512, 640, 768, 896, 960, 1024, 1280, 1536, 1792]
        se_size: 0
        use_se: 0
    -   kernel_size1: 1
        kernel_size2: SearchAxis(3)@[3, 5]
        kernel_size3: 1
        neck_channels: SearchAxis(960)@[512, 640, 768, 896, 960, 1024, 1280, 1536, 1792]
        se_size: 0
        use_se: 0
    num_blocks: SearchAxis(3)@[2, 3, 4]
    out_channels: SearchAxis(160)@[80, 96, 112, 128, 160, 192, 224, 256, 320]
    stride: 2
-   blocks:
    -   kernel_size1: 1
        kernel_size2: SearchAxis(3)@[3, 5]
        kernel_size3: 1
        neck_channels: SearchAxis(960)@[512, 640, 768, 896, 960, 1024, 1280, 1536, 1792]
        se_size: 0
        use_se: 0
    -   kernel_size1: 1
        kernel_size2: SearchAxis(3)@[3, 5]
        kernel_size3: 1
        neck_channels: SearchAxis(960)@[512, 640, 768, 896, 960, 1024, 1280, 1536, 1792]
        se_size: 0
        use_se: 0
    num_blocks: SearchAxis(1)@[1, 2]
    out_channels: SearchAxis(320)@[160, 192, 224, 256, 320, 384, 448, 512, 640]
    stride: 1
output_stage:
    out_channels: SearchAxis(1280)@[640, 768, 896, 1024, 1280, 1536, 1792, 2048, 2560]
resolution: 224
