act_type: relu
resolution: SearchAxis(224)@[192, 224, 256]
se_ratio: null
se_size: null
se_type: null
se_use: 0
stages:
-   block_type: GluonInputBlock
    in_channels: 3
    kernel_size: 3
    name: input_stage
    num_blocks: 1
    out_channels: SearchAxis(64)@[48, 64]
-   block_type: ResidualBlock
    grouch: SearchAxis(32)@[12, 24, 32, 48, 64]
    groups: 1
    kernel_size: SearchAxis(5)@[3, 5]
    name: stage1
    num_blocks: SearchAxis(7)@[5, 6, 7, 8]
    out_channels: SearchAxis(192)@[96, 128, 192, 256]
    stride: 1
-   block_type: ResidualBlock
    grouch: SearchAxis(96)@[48, 64, 96, 128]
    groups: 1
    kernel_size: SearchAxis(5)@[3, 5]
    name: stage2
    num_blocks: SearchAxis(7)@[5, 6, 7, 8]
    out_channels: SearchAxis(512)@[384, 512]
    stride: 2
-   block_type: ResidualBlock
    grouch: SearchAxis(256)@[192, 256]
    groups: 1
    kernel_size: SearchAxis(5)@[3, 5]
    name: stage3
    num_blocks: SearchAxis(7)@[6, 7, 8]
    out_channels: SearchAxis(1024)@[1024]
    stride: 2
-   block_type: ResidualBlock
    grouch: SearchAxis(512)@[512]
    groups: 1
    kernel_size: SearchAxis(5)@[3, 5]
    name: stage4
    num_blocks: SearchAxis(8)@[7, 8]
    out_channels: SearchAxis(2048)@[2048]
    stride: 2