env:
    backend: 'ncclx'
    bn_group: 1
    bn_sync_stat: False
net:
    backbone:
        arch: core.model.backbone.vggnet.vgg10
        lr_decay_mult: # listing all layers with param
             # [w_lr_mult, w_decay_mult, b_lr_mult, b_decay_mult]
             nn.Conv2d: [1, 1, 1, 1]
             nn.BatchNorm2d: [1, 1, 1, 1]
        kwargs: 
            layers_list: [64, 64, 'M', 128, 128, 'M', 256, 256, 256, 'M', 512, 512, 512]
            in_channels: 3
            batch_norm: False
            dilation: False
    head: 
        arch: core.model.head.mse_head.MseHead
        prev: backbone # must have for neck and head module
        kwargs:
            task_cfgs:
                crowd:
                     loss_type: 'mse'
                     dilation: True
                     backend_feat: [512, 512, 512, 256, 128, 64]
                     scale_factor: 1
        task_names:
            0:
                crowd: ['SHB']
strategy:
    task_type: 'crowd'
    task_mode: 'train'
    fp16: False
    scatter_mode: False
    max_iter: 160000
    base_lr: 0.000008
    lr_steps: [1000000]
    lr_mults: [1]
    momentum: 0.95
    weight_decay: 0.0005
    snapshot_freq: 400
    print_freq: 20
    save_path: '../Pattern_exp/SHB/crowd'
    load_name: ''
    pretrained_model: '/mnt/lustre/share/yangxu/part_B/vgg16-397923af.pth'
    workers: 4
    sampler: 'iter'
data:
    training_param:
        preprocessor: 'cv'
        final_height: 768
        final_width: 1024
        final_channel: 3
        normalize: True
        normalize_type: 'mean_std' 
        mean: [103.53,116.28,123.675] 
        std: [57.375, 57.12, 58.395] 
    SHB:
        type: 'crowd'
        task: 'ori_coord'
        train: True
        json_path: '/mnt/lustre/share/yangxu/part_B/jsons/Shanghai_PartB_train_768x1024_with_coord.json'
        img_prefix: '/mnt/lustre/share/yangxu/part_B/train_data/images'
        batch_size: 1
        ds_ratio: 8
        repeat_times: 1
        target_height: 768
        target_width: 1024
        sigma: 15
        density_thre: 0.08
        loss_weight: 2
test:
    strategy: 
        task_type: 'crowd-test'
        task_mode: 'test'
        scatter_mode: False
        load_path: ''
        workers: 0
        sampler: 'iter'
    testing_param:
        preprocessor: 'cv'
        final_height: 768
        final_width: 1024
        final_channel: 3
        normalize: True
        normalize_type: 'mean_std' 
        mean: [103.53,116.28,123.675] 
        std: [57.375, 57.12, 58.395] 
    SHB:
        type: 'crowd'
        task: 'ori_coord'
        train: False
        json_path: '/mnt/lustre/share/yangxu/part_B/jsons/Shanghai_PartB_test_768x1024_with_coord.json'
        img_prefix: '/mnt/lustre/share/yangxu/part_B/test_data/images'
        batch_size: 1
        ds_ratio: 8
        repeat_times: 1
        target_height: 768
        target_width: 1024
        sigma: 15
        density_thre: 0.08
        loss_weight: 2
