seed: 99
net:
    arch: mobile_v1
    kwargs:
        num_classes: 1000
        scale: 1.0
    #bn:
    #    group_size: 1
    #fp16:
    #    scale_factor: 1024
 
dataset:
  train:
    meta_file: /mnt/lustre/share/images/meta/train.txt
    image_dir: /mnt/lustre/share/images/train
    reader: pillow
    random_resize_crop: 224
    colorjitter: [0.2, 0.2, 0.2, 0.1]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: True
  test:
    meta_file: /mnt/lustre/share/images/meta/val.txt
    image_dir: /mnt/lustre/share/images/val
    reader: pillow
    resize: 256
    center_crop: [224, 224]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: False
  batch_size: 32
  workers: 4
 
trainer:
  max_epoch: 75
  test_freq: 75
  log_freq: 100
  label_smooth:
  optimizer:
    type: SGD
    kwargs:
      lr: 0.045
      momentum: 0.9
      weight_decay: 0.00004
  lr_scheduler:
    warmup_epochs: 0
    type: MultiStepLR
    kwargs:
      milestones: [30,60,90]
      gamma: 0.1
 
saver:
  #pretrian_model: /mnt/lustre/share/DSK/model_zoo/pytorch/imagenet/resnet50-19c8e357.pth
 # resume_model: ckpt_latest.pth_d7ccb963-0f3d-4651-b233-9f2be8a75a3f
 # load_pavi: True   # load pretrain/resume model from pavi
 # save_pavi: True   # add snapshot to pavi
  save_dir: checkpoints/mobile_v1   # save checkpoint locally
  save_epoch_freq: 10
  save_latest: False
  save_best: False
  sync_bn_stats: False  
 
#monitor:
 # type: pavi
 #  kwargs:
 #    project: zhujuan_demo
 #    task: mobile_v1_1x
 #    model: mobile_v1_1x
  # type: tensorboard
  # kwargs:
  #     logdir: tensorboard
