task:
    # Required (change partition, num_gpus or others where necessary)
    template: "sh runner/{framework}/train.sh pat_dev {gpus} {model} {py_args}"
    # Required
    search_args:
        - type: Nested
          value: [
                    # (un)commit your config here
                    # mmaction
                    {'framework': 'mmaction', 'gpus': 8, 'model': 'tsm_r50_video_1x1x8_100e_kinetics400_rgb', 'py_args': '--pavi --pavi-project parrots_test --data_reader MemcachedReader --seed 1024'},
                ]
    # Optional
    # callback: "cat"
    pre_callback: "python unitest/kill_job/parrots_test_callback_new.py {framework} {model} 0 benchmark"
    after_callback: "python unitest/kill_job/parrots_test_callback_new.py {framework} {model} 1 benchmark"

searcher:
    # Support GridSearcher, RandomSearcher, SkoptSearcher
    type: GridSearcher
    # Required
    reward_attribute: acc

scheduler:
    type: FIFO
    parallel_size: 8
    stop_criterion:
        max_tries: 100
    wait_to_run_time_thresh: 12 # inf

# Optional
pavi:
    compare:
        name: parrots.test.benchmark

# slurm_job_id_monitor: true
