dataset: # Required.
  type: cityscapes
  train:
    data_root: /mnt/lustre/share/HiLight/dataset/cityscapes
    data_list: /mnt/lustre/share/HiLight/dataset/cityscapes/fine_train.txt
    crop:
      type: rand
      size: [448, 896] # crop image with HxW size
  val:
    data_root: /mnt/lustre/share/HiLight/dataset/cityscapes
    data_list: /mnt/lustre/share/HiLight/dataset/cityscapes/fine_val.txt
    resize: [512, 1024]
    crop:
      type: center
      size: [448, 896] # crop image with HxW size
  batch_size: 2
  workers: 2
  flip: True
  GaussianBlur: False
  rand_resize: [0.5, 0.75]
  rand_rotation: [-5., 5.]
  mean: [123.675, 116.28, 103.53]
  std: [58.395, 57.12, 57.375]
  ignore_label: 255

trainer: # Required.
  epochs: 200
  start_epochs: 0
  optimizer:
    type: SGD
    kwargs:
      lr: 0.025
      momentum: 0.9
      weight_decay: 0.0005
  lr_scheduler:              # lr_scheduler = MultStepLR(optimizer, milestones=[9,14],gamma=0.1)
    mode: poly
    kwargs:
      power: 0.9

saver:
  snapshot_dir: checkpoints
  pretrain: ''

criterion:
  type: ohem
  kwargs:
    thresh: 0.6
    min_kept: 200000

net: # Required.
  num_classes: 19
  sync_bn: True
  encoder:
    type: pss.models.mobilenet_v2_plus.net_v2_plus
    kwargs:
      width_mult: 1
  decoder:
    type: pss.models.decoder.dec_mobilenet_v2_plus
    kwargs:
      aspp_out: 256
