dataset: # Required.
  type: cityscapes
  train:
    data_root: /mnt/lustre/share/HiLight/dataset/cityscapes
    data_list: /mnt/lustre/share/HiLight/dataset/cityscapes/fine_train.txt
    ceph_data_root: s3://parrots_model_data/DSK/datasets/cityscapes
    ceph_data_list: /mnt/lustre/share/HiLight/dataset/cityscapes/fine_train.txt
    crop:
      type: rand
      size: [713, 713] # crop image with HxW size
  val:
    data_root: /mnt/lustre/share/HiLight/dataset/cityscapes
    data_list: /mnt/lustre/share/HiLight/dataset/cityscapes/fine_val.txt
    ceph_data_root: s3://parrots_model_data/DSK/datasets/cityscapes
    ceph_data_list: /mnt/lustre/share/HiLight/dataset/cityscapes/fine_train.txt
    crop:
      type: center
      size: [713, 713] # crop image with HxW size
  batch_size: 1
  workers: 2
  flip: True
  GaussianBlur: True
  rand_resize: [0.5, 2.0]
  rand_rotation: [-10.0, 10.0]
  mean: [123.675, 116.28, 103.53]
  std: [58.395, 57.12, 57.375]
  ignore_label: 255

trainer: # Required.
  epochs: 1
  start_epochs: 0
  optimizer:
    type: SGD
    kwargs:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0005
  lr_scheduler:
    mode: poly
    kwargs:
      power: 0.9

saver:
  snapshot_dir: checkpoints
  pretrain: ''

criterion:
  type: ohem
  kwargs:
    thresh: 0.6
    min_kept: 200000

net: # Required.
  num_classes: 19
  sync_bn: True
  aux_loss:
    aux_plane: 1024
    loss_weight: 0.4
  encoder:
    type: pss.models.resnet.resnet50
    kwargs:
      zero_init_residual: True
      replace_stride_with_dilation: [False, True, True]  #layer0...1 is fixed, layer2...4
  decoder:
    type: pss.models.decoder.dec_pspnet
    kwargs:
      inner_planes: 512
      sizes: [1,2,3,6]
