dataset:
    workers: 2  
    batch_size: 8
    kwargs:
        input_h: 0
        input_w: 0
        downsample: 2 
        mean: [0.485,0.456,0.406]
        std: [0.229,0.224,0.225] 
        aug_cfg: 
            randresize: 
                scale: [0.75, 1.25]
            randcrop:
                crop_size: [400, 400]
            randgray: True
            randjitter: True 
            randflip: True
    train: 
        type: h5_sfa
        data_list: /mnt/lustre/share_data/parrots_model_data/SHA/data_list/sfa_train_list.txt
        ceph_data_list: /mnt/lustre/share_data/parrots_model_data/SHA/data_list/sfa_ceph_train_list.txt
    val: 
        type: h5_sfa 
        data_list: /mnt/lustre/share_data/parrots_model_data/SHA/data_list/sfa_test_list.txt 
        ceph_data_list: /mnt/lustre/share_data/parrots_model_data/SHA/data_list/sfa_ceph_test_list.txt
    test:  
        type: h5_sfa 
        data_list: /mnt/lustre/share_data/parrots_model_data/SHA/data_list/sfa_test_list.txt 
        ceph_data_list: /mnt/lustre/share_data/parrots_model_data/SHA/data_list/sfa_ceph_test_list.txt
    test_image: 
        type: dir
        data_root: /mnt/lustre/share_data/parrots_model_data/SHA/test_data/images/
        ceph_data_root: s3://parrots_model_data/crowd/SHA/test_data/images/
structure:
    backbone: vgg16_bn
    decoder: sfa_decoder 
    head: identity
    pretrain_model_path: ~ 
    middle_channels: [512, 64]
    scale_factor: 1
    metric: 
        type: eval_counting
train:
    loss:
        pixel_loss:
            type: L2Loss
            kwargs:
                reduction: sum
        att_loss:
            att_weight: 0.1
            kwargs:
                reduction: sum
    scheduler:
        epochs: 400
        milestones: [-1,1,100,150]
        gamma: 1
    optimizer:
        type: Adam
        kwargs:
            lr: 0.0001
    snapshot_freq: 5
    print_freq: 50
    graph_update_freq: 5000
test_image:
    num_vis: True
    ROI: [-1, -1, 10000, 10000]
    save_results: True
    save_path: vis_features