dataset:
    workers: 2  
    batch_size: 1
    kwargs:
        input_h: 0
        input_w: 0
        downsample: 8 
        mean: [0.485,0.456,0.406]
        std: [0.229,0.224,0.225] 
        aug_cfg: 
            randresize: 
                scale: [0.75, 1.25]
            #randcrop:
            #    crop_size: [1024, 720]
            randgray: True
            randjitter: True 
            randflip: True
    train: 
        type: h5
        data_list: /mnt/lustre/share_data/parrots_model_data/SHA/data_list/train_list.txt
        ceph_data_list: /mnt/lustre/share_data/parrots_model_data/SHA/data_list/ceph_train_list.txt
    val: 
        type: h5 
        data_list: /mnt/lustre/share_data/parrots_model_data/SHA/data_list/test_list.txt 
        ceph_data_list: /mnt/lustre/share_data/parrots_model_data/SHA/data_list/ceph_test_list.txt
    test:  
        type: h5 
        data_list: /mnt/lustre/share_data/parrots_model_data/SHA/data_list/test_list.txt 
        ceph_data_list: /mnt/lustre/share_data/parrots_model_data/SHA/data_list/ceph_test_list.txt
    test_image: 
        type: dir
        data_root: /mnt/lustre/share_data/parrots_model_data/SHA/train_data/images/
        ceph_data_root: s3://parrots_model_data/crowd/SHA/test_data/images/
structure:
    backbone: vgg16
    decoder: CSR_decoder 
    head: count
    pretrain_model_path: /mnt/lustre/share/DSK/model_zoo/pytorch/imagenet/vgg16-397923af.pth 
    middle_channels: [512, 64]
    scale_factor: 1
    metric: 
        type: eval_counting
train:
    loss:
        pixel_loss:
            type: L2Loss
            kwargs:
                reduction: sum
    scheduler:
        epochs: 400
        milestones: [-1,1,100,150]
        gamma: 1
    optimizer:
        type: SGD
        kwargs:
            lr: 0.0000008
            weight_decay: 0.0005
            momentum: 0.95
    snapshot_freq: 5
    print_freq: 50
    graph_update_freq: 5000
test_image:
    num_vis: True
    ROI: [0, 80, 240, 160]
    save_results: True
    save_path: vis_features